### ISSUE TITLE
S3 ClientException: HttpBody type is not supported 

### ISSUE THREAD

**Issue by clementgayvallet** [awslabs/aws-sdk-kotlin#1014]
### Describe the bug

The new [ResponseLengthValidationInterceptor](https://github.com/awslabs/smithy-kotlin/blob/6811a975e3be2df060584326b8461b67f265b196/runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/interceptors/ResponseLengthValidationInterceptor.kt#L21) doesn't support the [HttpBody.Empty](https://github.com/awslabs/smithy-kotlin/blob/6811a975e3be2df060584326b8461b67f265b196/runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/HttpBody.kt#L40) type with a `Content-Length: 0` header and throws a ClientException.

### Expected behavior

The [HttpBody.toLengthValidatingBody] extension function should handle the `HttpBody.Empty` type and check if the `contentLength` is zero.

### Current behavior

When the response from s3 has an empty body **and** contains a `Content-Lenght` header then a ClientException is thrown:
```
aws.smithy.kotlin.runtime.ClientException: HttpBody type is not supported
	at aws.smithy.kotlin.runtime.http.interceptors.ResponseLengthValidationInterceptorKt.toLengthValidatingBody(ResponseLengthValidationInterceptor.kt:35)
	at aws.smithy.kotlin.runtime.http.interceptors.ResponseLengthValidationInterceptorKt.access$toLengthValidatingBody(ResponseLengthValidationInterceptor.kt:1)
	at aws.smithy.kotlin.runtime.http.interceptors.ResponseLengthValidationInterceptor.modifyBeforeDeserialization(ResponseLengthValidationInterceptor.kt:26)
	at aws.smithy.kotlin.runtime.http.interceptors.InterceptorExecutor.modifyBeforeDeserialization(InterceptorExecutor.kt:236)
	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:321)
	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler$call$1.invokeSuspend(SdkOperationExecution.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
``` 

### Steps to Reproduce

Call S3 GetObject for an object that exists but has an empty content:

```
val client = S3Client.fromEnvironment { }
client.getObject {
    bucket = "my-bucket"
    key = "my-empty-object"
} // Throws exception
```

### AWS Kotlin SDK version used

0.29.1-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Fedora 38

**Comment by ianbotsf** [comment]
Thanks for the bug report @clementgayvallet. I've reproduced the issue and should have a fix ready to PR later today!

**Comment by ianbotsf** [comment]
The fix for this issue has been merged to **main** and should be present in this week's release, tentatively scheduled for Thursday, Aug 17.
