### ISSUE TITLE
getObjectAttributes fails with "We encountered an internal error. Please try again." if key contains chinese characters

### ISSUE THREAD

**Issue by acarlsen** [awslabs/aws-sdk-kotlin#1142]
### Describe the bug

In my scenario I upload a file using S3 Client putObject method, key string contains chinese characters.
For example a file named 0103雲端備份訂價表.xlsx.

The upload works fine.

I then want to get attributes of the uploaded file to verify different things using getObjectAttributes - I use the same key as for upload. This fails with the following error. 

```
aws.sdk.kotlin.services.s3.model.S3Exception: We encountered an internal error. Please try again.
at aws.sdk.kotlin.services.s3.serde.GetObjectAttributesOperationDeserializerKt.throwGetObjectAttributesError(GetObjectAttributesOperationDeserializer.kt:81)
at aws.sdk.kotlin.services.s3.serde.GetObjectAttributesOperationDeserializerKt.access$throwGetObjectAttributesError(GetObjectAttributesOperationDeserializer.kt:1)
at aws.sdk.kotlin.services.s3.serde.GetObjectAttributesOperationDeserializerKt$throwGetObjectAttributesError$1.invokeSuspend(Unknown Source:13)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
```

### Expected behavior

I expect getObjectAttributes function call to not fail.

### Current behavior

Calling getObjectAttributes works for other keys, but fails consistently for keys with chinese characters (and also possibly other special characters). It works with Java SDK (getObjectMetadata).

### Steps to Reproduce

Upload a file to a bucket:
```
val request = PutObjectRequest {
    bucket = "somebucket"
    key = "0103雲端備份訂價表.xlsx"
    body = file.asByteStream()
}
s3Client.putObject(request)
```

Try to get object attributes:
```
val request = GetObjectAttributesRequest {
    bucket = "somebucket"
    key = "0103雲端備份訂價表.xlsx"
    objectAttributes = listOf(
       ObjectAttributes.ObjectSize,
       ObjectAttributes.Checksum,
    )
}
s3Client.getObjectAttributes(request)
```

### Possible Solution

None

### Context

I want to get metadata for an object with chinese characters in key.

### AWS Kotlin SDK version used

1.0.8

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Android 14

**Comment by acarlsen** [comment]
Just FYI I should have been more clear, I meant it worked in Java SDK for Android - the SDK for Android doesn't seem to have the getObjectAttributes method at all.

**Comment by aajtodd** [comment]
Yeah under the hood that method is just calling the [HeadObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html) operation. I'm not sure why it's renamed in the Android SDK.

```kotlin
val metadata = s3.headObject { 
    bucket = myBucket
    key = myKey
}

println(metadata)
```


See the Kotlin API ref docs for [headObject](https://sdk.amazonaws.com/kotlin/api/latest/s3/aws.sdk.kotlin.services.s3/head-object.html)

**Comment by acarlsen** [comment]
Thanks, that works fine. :-)

**Comment by lauzadis** [comment]
Hi, S3 has fixed this issue in their backend and I verified it's not a problem anymore. Thanks for the report!
