### ISSUE TITLE
SQS doesn't work when Android device enters Doze mode

### ISSUE THREAD

**Issue by ScottRoo** [awslabs/aws-sdk-kotlin#1264]
### Describe the bug

I'm not sure if this is an issue with SQS or Android itself so I'm hoping that you may be able to help me narrow it down.

I'm using SQS long polling in an Android app, the app has been whitelisted from being restricted when the device enters [doze mode ](https://developer.android.com/training/monitoring-device-state/doze-standby), yet when Doze mode is activated SQS continuously fails to receive messages.
	
I believe the whitelisting is working as the app has network access as other network requests succeed, it's just SQS that appears to be failing internally. I'm hoping to understand how SQS functions to try and understand what may be causing this.

### Expected behavior

SQS continues to work when an Android device enters Doze mode. 

### Current behavior

SQS continuously fails to receive messages (we use an exponential backoff retry)

> Caused by: java.net.SocketTimeoutException: failed to connect to /127.0.0.1 (port 39781) from /127.0.0.1 (port 39468) after 2000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:190)
	at libcore.io.IoBridge.connect(IoBridge.java:134)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:254)
	at okhttp3.internal.connection.ConnectPlan.connectTcp(ConnectPlan.kt:128)
	at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(FastFallbackExchangeFinder.kt:138)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:117)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Steps to Reproduce

I haven't been able to reproduce this locally, I'm going based on error logs. I suspect this problem is caused by the device / OS rather than SQS but I can't work out what restrictions Android may place on an app that would cause SQS to fail in this way.

### AWS Kotlin SDK version used

1.0.50

### Platform (JVM/JS/Native)

Android

### Operating System and version

Android 11

**Comment by aajtodd** [comment]
Thanks for reaching out.

> failed to connect to /127.0.0.1 (port 39781)

It would appear you are failing to connect to localhost?

Turning on trace logging and sharing logs would be helpful. 

---

This certainly seems Android related though and not AWS or other external host specific based on the description given. If you have a reproduction that you think points to the SDK at fault we'd be happy to take a closer look but there isn't enough to go on here.

**Comment by ScottRoo** [comment]
Thanks @aajtodd 

I appreciate the details are pretty light, I don't have much to go on myself, I can't even recreate it locally.

>It would appear you are failing to connect to localhost?

I assumed this was a quirk of how the library functioned internally, we provide SQS with a proper url so I'm not sure where this is coming from, nor why it only happens when the device enters Doze.

I've reached out to the device manufacturer directly as I'm confident it's something on there end, but raised this here to see if there was any further context I could give them.

**Comment by aajtodd** [comment]
Ok if you can get trace logs that would probably help.

**Comment by ScottRoo** [comment]
On the off chance this is helpful to someone experiencing the same issue, we also had to whitelist the following packages from Doze mode.

```
com.android.pacprocessor
com.android.proxyhandler
```
