### ISSUE TITLE
AWS SDK does not work with ki shell

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#303]
## Describe the bug
I'm unable to use an AWS client from the [interactive Kotlin shell `ki`](https://blog.jetbrains.com/kotlin/2021/04/ki-the-next-interactive-shell-for-kotlin/).

## Expected Behavior
* I can construct a service client.

## Current Behavior
When I construct a service client, I get the following exception:

```
[1] :dependsOn aws.sdk.kotlin:s3:0.4.0-alpha
[2] import aws.sdk.kotlin.services.s3.S3Client 
[3] val s3c = S3Client { region = "us-east-2" }
java.lang.ExceptionInInitializerError
	at software.amazon.awssdk.crt.CrtResource.<clinit>(CrtResource.java:100)
	at aws.sdk.kotlin.crt.io.TlsContext.<init>(TlsContextJVM.kt:15)
	at aws.sdk.kotlin.runtime.http.engine.crt.CrtHttpEngine.<init>(CrtHttpEngine.kt:29)
	at aws.sdk.kotlin.services.s3.DefaultS3Client.<init>(DefaultS3Client.kt:30)
	at aws.sdk.kotlin.services.s3.S3Client$Companion.invoke(S3Client.kt:31)
	at Line_6.<init>(Line_6.kts:1)

```

## Steps to Reproduce

Run ki shell, type in commands as specified in the `Current Behavior` section.

## Your Environment

* AWS Kotlin SDK version used: 0.4.0-alpha
* Platform (JVM/JS/Native): JVM
* Operating System and version: Ubuntu Linux 20.04

**Comment by lauzadis** [comment]
I was able to get the latest version of the SDK working in a Kotlin Script (which is what `ki` creates under the hood). `ki` itself still does not work because it's compiled using an old version of Kotlin. In general the project seems to be unmaintained.

Kotlin Script (works)
```
```
