### ISSUE TITLE
Error thrown when submitting document to CloudSearch Domain

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#338]
## Describe the bug

Unable to successfully upload a document to a CloudSearch domain.

## Expected Behavior

Assuming a domain has been created in CloudSearch, and that domain is specified when constructing a client, the following code should work without error:

```kotlin
    @Test
    fun cloudSearchDomainTest() = runBlocking {
        val client = CloudSearchDomainClient {
            sdkLogMode = SdkLogMode.LogRequestWithBody.plus(SdkLogMode.LogResponseWithBody)
            region = "us-east-1"
            endpointResolver = StaticEndpointResolver(Endpoint("somegenerateddomainprefix.us-east-1.cloudsearch.amazonaws.com", "HTTPS"))
        }

        val response = client.uploadDocuments { documents = ByteStream.fromString("<html>boo</html>") }

        assertTrue(response.adds > 0)
    }
```

## Current Behavior

When running the unit test I observe the following error:

```
{ ["Content-Type header must be one of ['application/xml', 'application/json'] (was application/octet-stream)"] }
DocumentServiceException(message={ ["Content-Type header must be one of ['application/xml', 'application/json'] (was application/octet-stream)"] },status=error)
	at aws.sdk.kotlin.services.cloudsearchdomain.model.DocumentServiceException$BuilderImpl.build(DocumentServiceException.kt:95)
	at aws.sdk.kotlin.services.cloudsearchdomain.transform.DocumentServiceExceptionDeserializer.deserialize(DocumentServiceExceptionDeserializer.kt:34)
	at aws.sdk.kotlin.services.cloudsearchdomain.transform.UploadDocumentsOperationDeserializerKt.throwUploadDocumentsError(UploadDocumentsOperationDeserializer.kt:100)
	at aws.sdk.kotlin.services.cloudsearchdomain.transform.UploadDocumentsOperationDeserializerKt.access$throwUploadDocumentsError(UploadDocumentsOperationDeserializer.kt:1)
	at aws.sdk.kotlin.services.cloudsearchdomain.transform.UploadDocumentsOperationDeserializer.deserialize(UploadDocumentsOperationDeserializer.kt:36)
	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)

```

## Steps to Reproduce
1. Create a cloudsearch domain in AWS acct
2. Get the endpoint url, pass that to csd client
3. call `uploadDocuments` on client.

## Your Environment

* AWS Kotlin SDK version used: 0.6.2-SNAPSHOT
* Platform (JVM/JS/Native): java 11
* Operating System and version: Ubuntu 20.04

**Comment by kggilmer** [comment]
It was pointed out that I may need to specify the content type along with the document.  Updated unit test:

```kotlin
    @Test
    fun someTest() = runBlocking {
        val client = CloudSearchDomainClient {
            sdkLogMode = SdkLogMode.LogRequestWithBody.plus(SdkLogMode.LogResponseWithBody)
            region = "us-east-1"
            endpointResolver = StaticEndpointResolver(Endpoint("doc-movies-vx56552a3j2ljt3cne7jayoi6i.us-east-1.cloudsearch.amazonaws.com", "HTTPS"))
        }

        val response = client.uploadDocuments {
            documents = ByteStream.fromString("<html>boo</html>")
            contentType = ContentType.fromValue("application/xml")
        }

        assertTrue(response.adds > 0)
    }
```

I receive the following error running the test:

```
{ ["Unknown top level XML element: html (expected <batch>)"] }
DocumentServiceException(message={ ["Unknown top level XML element: html (expected <batch>)"] },status=error)
	at aws.sdk.kotlin.services.cloudsearchdomain.model.DocumentServiceException$BuilderImpl.build(DocumentServiceException.kt:95)
	at aws.sdk.kotlin.services.cloudsearchdomain.transform.DocumentServiceExceptionDeserializer.deserialize(DocumentServiceExceptionDeserializer.kt:34)
	at aws.sdk.kotlin.services.cloudsearchdomain.transform.UploadDocumentsOperationDeserializerKt.throwUploadDocumentsError(UploadDocumentsOperationDeserializer.kt:100)
	at aws.sdk.kotlin.services.cloudsearchdomain.transform.UploadDocumentsOperationDeserializerKt.access$throwUploadDocumentsError(UploadDocumentsOperationDeserializer.kt:1)
	at aws.sdk.kotlin.services.cloudsearchdomain.transform.UploadDocumentsOperationDeserializer.deserialize(UploadDocumentsOperationDeserializer.kt:36)
	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)
	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)
	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:153)
...
```

**Comment by kggilmer** [comment]
Verified that I was using the service incorrectly.  The following sample works:

```kotlin
    @Test
    fun someTest() = runBlocking {
        val client = CloudSearchDomainClient {
            sdkLogMode = SdkLogMode.LogRequestWithBody.plus(SdkLogMode.LogResponseWithBody)
            region = "us-east-1"
            endpointResolver = StaticEndpointResolver(Endpoint("doc-movies-vx56552a3j2ljt3cne7jayoi6i.us-east-1.cloudsearch.amazonaws.com", "HTTPS"))
        }

        val batchXml = """
            <batch>
             <add  id="tt0484562">
              <field name="content"><![CDATA[<html>boo</html>]]></field>
             </add>
            </batch>
        """.trimIndent()

        val response = client.uploadDocuments {
            documents = ByteStream.fromString(batchXml)
            contentType = ContentType.fromValue("application/xml")
        }

        assertTrue(response.adds > 0)
    }
```
