### ISSUE TITLE
Segfault in CRT HTTP engine connection shutdown

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-sdk-kotlin#413]
## Describe the bug

One of our [async stress tests](https://github.com/awslabs/aws-sdk-kotlin/blob/v0.9.1-alpha/aws-runtime/http-client-engine-crt/jvm/test/aws/sdk/kotlin/runtime/http/engine/crt/AsyncStressTest.kt#L75) for the CRT HTTP engine is segfaulting on windows. 

```
2021-11-10T16:50:20.6269236Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel-bootstrap] - id=000001AEABDCDA20: channel 000001AEABC0D800 shutdown with error 0.
2021-11-10T16:50:20.6270298Z [INFO] [2021-11-10T16:48:43Z] [000010d4] [http-connection] - 000001AEAD1C45B0: Client shutdown completed with error 0 (AWS_ERROR_SUCCESS).
2021-11-10T16:50:20.6271351Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: shutdown received for connection (id=000001AEAD1C45B0)
2021-11-10T16:50:20.6272476Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: snapshot - state=1, idle_connection_count=0, pending_acquire_count=695, pending_connect_count=1, vended_connection_count=15, open_connection_count=15, ref_count=1
2021-11-10T16:50:20.6273464Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0D800: destroying channel.
2021-11-10T16:50:20.6274148Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [socket] - id=000001AEAC5CEB90, handle=FFFFFFFFFFFFFFFF: cleaning up socket.
2021-11-10T16:50:20.6274854Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [socket] - id=000001AEAC5CEB90 handle=FFFFFFFFFFFFFFFF: closing
2021-11-10T16:50:20.6275597Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel-bootstrap] - id=000001AEABDCDA20: releasing bootstrap reference
2021-11-10T16:50:20.6276397Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [task-scheduler] - id=000001AEAD56DE70: Running on_channel_setup_complete task with <Running> status
2021-11-10T16:50:20.6277154Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: setup complete, notifying caller.
2021-11-10T16:50:20.6278187Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: message pool 000001AEADBDCDB0 found in event-loop local storage: using it.
2021-11-10T16:50:20.6279287Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel-bootstrap] - id=000001AEABDCDA20: channel 000001AEABC0B400 setup succeeded: bootstrapping.
2021-11-10T16:50:20.6280343Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: creating new slot 000001AEAB4F3610.
2021-11-10T16:50:20.6281291Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [socket-handler] - id=000001AEABE15510: Socket handler created with max_read_size of 262144
2021-11-10T16:50:20.6282185Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket] - id=000001AEAC5CC970 handle=00000000000008B0: subscribing to readable event
2021-11-10T16:50:20.6283430Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel-bootstrap] - id=000001AEABDCDA20: Setting up socket handler on channel 000001AEABC0B400 with handler 000001AEABE15510 on slot 000001AEAB4F3610.
2021-11-10T16:50:20.6284338Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: scheduling task with wrapper task id 000001AEABC0B668.
2021-11-10T16:50:20.6285093Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: scheduling task 000001AEABC0B668 in-thread for timestamp 0
2021-11-10T16:50:20.6285933Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [task-scheduler] - id=000001AEABC0B668: Scheduling window update task task for immediate execution
2021-11-10T16:50:20.6286867Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [http-connection] - static: Socket connected, creating client connection object.
2021-11-10T16:50:20.6287651Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: creating new slot 000001AEAB4F3A90.
2021-11-10T16:50:20.6288593Z [INFO] [2021-11-10T16:48:43Z] [000010d4] [http-connection] - id=000001AEAD1C0FF0: HTTP/1.1 client connection established.
2021-11-10T16:50:20.6289497Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: Received new connection (id=000001AEAD1C0FF0) from http layer
2021-11-10T16:50:20.6290403Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: Grabbing pooled connection (000001AEAD1C0FF0)
2021-11-10T16:50:20.6291706Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: snapshot - state=1, idle_connection_count=0, pending_acquire_count=694, pending_connect_count=0, vended_connection_count=16, open_connection_count=16, ref_count=1
2021-11-10T16:50:20.6292957Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: Successfully completed connection acquisition with connection id=000001AEAD1C0FF0
2021-11-10T16:50:20.6293988Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [http-connection] - ConnManager Acquired Conn: conn: 000001AEAD1C0FF0, manager: 000001AEABDD7370, err_code: 0,  err_str: Success.
2021-11-10T16:50:20.6294933Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: detected more scheduled tasks with the next occurring at 0, using timeout of 0.
2021-11-10T16:50:20.6295695Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: waiting for a maximum of 0 ms
2021-11-10T16:50:20.6296497Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: running scheduled tasks.
2021-11-10T16:50:20.6297358Z [DEBU# A fatal error has been detected by the Java Runtime Environment:
2021-11-10T16:50:20.6298104Z #
2021-11-10T16:50:20.6298599Z #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffccbc0da13, pid=436, tid=5812
2021-11-10T16:50:20.6299071Z #
2021-11-10T16:50:20.6299557Z # JRE version: OpenJDK Runtime Environment Temurin-11.0.13+8 (11.0.13+8) (build 11.0.13+8)
2021-11-10T16:50:20.6300736Z # Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (11.0.13+8, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
2021-11-10T16:50:20.6301502Z # Problematic frame:
2021-11-10T16:50:20.6301953Z # C  [AWSCRT_16365629109837760066350924725629aws-crt-jni.dll+0xda13]
2021-11-10T16:50:20.6302330Z #
2021-11-10T16:50:20.6303015Z # Core dump will be written. Default location: D:\a\aws-sdk-kotlin\aws-sdk-kotlin\aws-runtime\http-client-engine-crt\hs_err_pid436.mdmp
2021-11-10T16:50:20.6303887Z #
2021-11-10T16:50:20.6304270Z # An error report file with more information is saved as:
2021-11-10T16:50:20.6305026Z # D:\a\aws-sdk-kotlin\aws-sdk-kotlin\aws-runtime\http-client-engine-crt\hs_err_pid436.log
2021-11-10T16:50:20.6306498Z Compiled method (nm)   16764 6397     n 0       software.amazon.awssdk.crt.http.HttpClientConnection::httpClientConnectionShutdown (native)
2021-11-10T16:50:20.6308172Z  total in heap  [0x000001ae9fd04a90,0x000001ae9fd04e68] = 984
2021-11-10T16:50:20.6308811Z  relocation     [0x000001ae9fd04c08,0x000001ae9fd04c38] = 48
2021-11-10T16:50:20.6309567Z  main code      [0x000001ae9fd04c40,0x000001ae9fd04e60] = 544
2021-11-10T16:50:20.6310179Z  oops           [0x000001ae9fd04e60,0x000001ae9fd04e68] = 8
2021-11-10T16:50:20.6310582Z #
2021-11-10T16:50:20.6310958Z # If you would like to submit a bug report, please visit:
2021-11-10T16:50:20.6311587Z #   https://github.com/adoptium/adoptium-support/issues
2021-11-10T16:50:20.6312481Z # The crash happened outside the Java Virtual Machine in native code.
2021-11-10T16:50:20.6313096Z # See problematic frame for where to report the bug.
2021-11-10T16:50:20.6313482Z #
2021-11-10T16:50:20.6314045Z G] [2021-11-10T16:48:43Z] [000010d4] [task-scheduler] - id=000001AEABC0B668: Running window update task task with <Running> status
2021-11-10T16:50:20.6315302Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket-handler] - id=000001AEABE15510: increment read window message received, scheduling task for another read operation.
2021-11-10T16:50:20.6316234Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: scheduling task with wrapper task id 000001AEABE15548.
2021-11-10T16:50:20.6317045Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: scheduling task 000001AEABE15548 in-thread for timestamp 0
2021-11-10T16:50:20.6318064Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [task-scheduler] - id=000001AEABE15548: Scheduling socket_handler_read_on_window_increment task for immediate execution
2021-11-10T16:50:20.6319063Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: detected more scheduled tasks with the next occurring at 0, using timeout of 0.
2021-11-10T16:50:20.6319863Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: waiting for a maximum of 0 ms
2021-11-10T16:50:20.6320513Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: running scheduled tasks.
2021-11-10T16:50:20.6321859Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [task-scheduler] - id=000001AEABE15548: Running socket_handler_read_on_window_increment task with <Running> status
2021-11-10T16:50:20.6322785Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket-handler] - id=000001AEABE15510: invoking read. Downstream window 262144, max_to_read 262144
2021-11-10T16:50:20.6332389Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: acquired message 000001AEB3D52740 of capacity 262144 from pool 000001AEADBDCDB0. Requested size was 262144
2021-11-10T16:50:20.6333367Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket] - id=000001AEAC5CC970 handle=00000000000008B0: reading from socket
2021-11-10T16:50:20.6334396Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket] - id=000001AEAC5CC970 handle=00000000000008B0: read would block, scheduling 0 byte read and returning
2021-11-10T16:50:20.6335476Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket-handler] - id=000001AEAB4F3630: total read on this tick 0
2021-11-10T16:50:20.6336438Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket-handler] - id=000001AEABE15510: out of data to read on socket. Waiting on event-loop notification.
2021-11-10T16:50:20.6337436Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: detected more scheduled tasks with the next occurring at 859251931100, using timeout of 493.
2021-11-10T16:50:20.6338377Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: waiting for a maximum of 493 ms
2021-11-10T16:50:20.6338769Z 
```

## Steps to Reproduce

I've only been able to reproduce this in CI so far. Here is a failing CI run with full logs and JVM dump as an artifact:
https://github.com/awslabs/aws-sdk-kotlin/actions/runs/1446034029

## Possible Solution

CRT team is currently investigating

**Comment by stiost** [comment]
I'm experiencing the same issue on Linux with OpenJDK 11 and 17. It fails if I'm launching 20 coroutines concurrently, but works on with 5. I'm using the SDK to upload about 2000 files of 100kb - 2mb to S3.

**Comment by aajtodd** [comment]
@stiost Thanks for reporting this. Do you have some example code you might be able to share that triggers this on Linux? We still have only been able to reproduce this in CI on Windows. Any other details about your environment may help as well.

**Comment by Yuri-Bartochevis** [comment]
I've got a similar error executing local w/ macOS system + localstack
JDK: OpenJDK11 / OpenJDK8

```
   SnsClient {
            credentialsProvider = DefaultChainCredentialsProvider()
            region = AWS_REGION
            endpointResolver = AwsEndpointResolver { _, _ -> AwsEndpoint(AWS_ENDPOINT) }
        }.use { snsClient ->
            val result = snsClient.publish(request)
        }
    }
```

console:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001161ca134, pid=32525, tid=0x000000000000a503
#
# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [AWSCRT_16392682446068781761167310731634libaws-crt-jni.dylib+0x9134]  Java_software_amazon_awssdk_crt_http_HttpClientConnection_httpClientConnectionShutdown+0x4
```

File w/ more explanation: hs_err_pid.log
```
Stack: [0x0000700003cf4000,0x0000700003df4000],  sp=0x0000700003defda0,  free space=1007k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [AWSCRT_16392682446068781761167310731634libaws-crt-jni.dylib+0x9134]  Java_software_amazon_awssdk_crt_http_HttpClientConnection_httpClientConnectionShutdown+0x4
j  software.amazon.awssdk.crt.http.HttpClientConnection.httpClientConnectionShutdown(J)V+0
j  software.amazon.awssdk.crt.http.HttpClientConnection.shutdown()V+4
j  aws.sdk.kotlin.crt.http.HttpClientConnectionJVM.shutdown()V+4
j  aws.sdk.kotlin.runtime.http.engine.crt.SdkStreamResponseHandler.complete$http_client_engine_crt()V+56
j  aws.sdk.kotlin.runtime.http.engine.crt.CrtHttpEngine$roundTrip$2.invoke(Ljava/lang/Throwable;)V+4
j  aws.sdk.kotlin.runtime.http.engine.crt.CrtHttpEngine$roundTrip$2.invoke(Ljava/lang/Object;)Ljava/lang/Object;+5
j  kotlinx.coroutines.InvokeOnCompletion.invoke(Ljava/lang/Throwable;)V+5
j  kotlinx.coroutines.JobSupport.notifyCompletion(Lkotlinx/coroutines/NodeList;Ljava/lang/Throwable;)V+64
j  kotlinx.coroutines.JobSupport.completeStateFinalization(Lkotlinx/coroutines/Incomplete;Ljava/lang/Object;)V+169
j  kotlinx.coroutines.JobSupport.finalizeFinishingState(Lkotlinx/coroutines/JobSupport$Finishing;Ljava/lang/Object;)Ljava/lang/Object;+358
j  kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(Lkotlinx/coroutines/Incomplete;Ljava/lang/Object;)Ljava/lang/Object;+367
j  kotlinx.coroutines.JobSupport.tryMakeCompleting(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;+63
j  kotlinx.coroutines.JobSupport.cancelMakeCompleting(Ljava/lang/Object;)Ljava/lang/Object;+67
j  kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(Ljava/lang/Object;)Z+13
j  kotlinx.coroutines.JobSupport.cancelInternal(Ljava/lang/Throwable;)V+2
j  kotlinx.coroutines.JobSupport.cancel(Ljava/util/concurrent/CancellationException;)V+45
j  aws.smithy.kotlin.runtime.http.engine.CoroutineUtilsKt$attachToOuterJob$cleanupHandler$1.invoke(Ljava/lang/Throwable;)V+22
j  aws.smithy.kotlin.runtime.http.engine.CoroutineUtilsKt$attachToOuterJob$cleanupHandler$1.invoke(Ljava/lang/Object;)Ljava/lang/Object;+5
```

**Comment by kiiadi** [comment]
Same thing happening on Mac:

```kt
val s3 = S3Client.fromEnvironment()
repeat(10000) {
    launch {
        val number = it.toString().padStart(8, '0')

        setOf("foo", "bar", "baz").map {
            async {
                gate.withPermit {
                    s3.putObject {
                        bucket = bucketName
                        this.key = "$number/$it"
                        body = ByteStream.fromString("boop")
                    }
                }
            }
        }.awaitAll()
    }
}
```

**Comment by aajtodd** [comment]
Status update:

I've added a bunch of debugging output to crt-java to track close/shutdown calls. It looks like the Kotlin SDK is in fact invoking `shutdown()` after `close()`. It does so because it's handling the same exception twice as it turns out.

The coroutine that gets cancelled causes an exception to be handled [here](https://github.com/awslabs/aws-sdk-kotlin/blob/main/aws-runtime/http-client-engine-crt/common/src/aws/sdk/kotlin/runtime/http/engine/crt/CrtHttpEngine.kt#L103). The second time is triggered from the completion handler registered [here](https://github.com/awslabs/aws-sdk-kotlin/blob/main/aws-runtime/http-client-engine-crt/common/src/aws/sdk/kotlin/runtime/http/engine/crt/CrtHttpEngine.kt#L90-L93) (which ends up in this [function](https://github.com/awslabs/aws-sdk-kotlin/blob/main/aws-runtime/http-client-engine-crt/common/src/aws/sdk/kotlin/runtime/http/engine/crt/SdkStreamResponseHandler.kt#L162-L173)).

```
cancelling
roundTrip exception: id=3 throwable=java.util.concurrent.CancellationException: Parent job is Cancelling; conn=aws.sdk.kotlin.crt.http.HttpClientConnectionJVM@7d7758be jniConn=software.amazon.awssdk.crt.http.HttpClientConnection@2bdd8394
[INFO] [2022-01-07T21:39:44Z] [00007000053f1000] [Unknown] - software.amazon.awssdk.crt.http.HttpClientConnection@2bdd8394::releaseNativeHandle(); nativeHandle=140482209647888;
        stack:java.lang.RuntimeException
        at software.amazon.awssdk.crt.http.HttpClientConnection.releaseNativeHandle(HttpClientConnection.java:74)
        at software.amazon.awssdk.crt.CrtResource.release(CrtResource.java:218)
        at software.amazon.awssdk.crt.CrtResource.decRef(CrtResource.java:294)
        at software.amazon.awssdk.crt.CrtResource.close(CrtResource.java:276)
        at software.amazon.awssdk.crt.http.HttpClientConnectionManager.releaseConnection(HttpClientConnectionManager.java:162)
        at aws.sdk.kotlin.crt.http.HttpClientConnectionManager.releaseConnection(HttpClientConnectionManagerJVM.kt:42)
        at aws.sdk.kotlin.runtime.http.engine.crt.CrtHttpEngine.roundTrip(CrtHttpEngine.kt:108)
        at aws.sdk.kotlin.runtime.http.engine.crt.CrtHttpEngine$roundTrip$1.invokeSuspend(CrtHttpEngine.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at aws.sdk.kotlin.example.MainKt.main(Main.kt:33)
        at aws.sdk.kotlin.example.MainKt.main(Main.kt)

call complete: id=3, handler=aws.sdk.kotlin.runtime.http.engine.crt.SdkStreamResponseHandler@68746f22; throwable=java.util.concurrent.CancellationException: Parent job is Cancelling; conn=aws.sdk.kotlin.crt.http.HttpClientConnectionJVM@7d7758be jniConn=software.amazon.awssdk.crt.http.HttpClientConnection@2bdd8394
forcing closed! handler=aws.sdk.kotlin.runtime.http.engine.crt.SdkStreamResponseHandler@68746f22; forceClose=true; conn=aws.sdk.kotlin.crt.http.HttpClientConnectionJVM@7d7758be jniConn=software.amazon.awssdk.crt.http.HttpClientConnection@2bdd8394; stream=null
[INFO] [2022-01-07T21:39:44Z] [00007000053f1000] [Unknown] - software.amazon.awssdk.crt.http.HttpClientConnection@2bdd8394::shutdown(); nativeHandle=0
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000135684d84, pid=6686, tid=5891
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.10.9.1 (11.0.10+9) (build 11.0.10+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (11.0.10+9-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [AWSCRT_16415915833975983087226254389958libaws-crt-jni.dylib+0x9d84]  Java_software_amazon_awssdk_crt_http_HttpClientConnection_httpClientConnectionShutdown+0x4
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/todaaron/sandbox/IdeaProjects/sdk-sandbox/hs_err_pid6686.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-11/issues/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
./run.sh: line 6:  6686 Abort trap: 6           java -Daws.crt.log.level=Info -Daws.crt.debugnative=false -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG -Dorg.slf4j.simpleLogger.showDateTime=true -Dfile.encoding=UTF-8 -Daws.bucket=aaron22-throwaway -cp ./build/libs/sdk-sandbox-1.0-SNAPSHOT-all.jar aws.sdk.kotlin.example.MainKt
```

These were meant to handle exceptions at different times in the execution of a request to ensure a connection is returned to the pool. It turns out an exception can trigger both paths (since one is registered on the coroutine job). Depending on the state of the connection we can end up calling `shutdown()` on an already released connection.
