### ISSUE TITLE
S3: 304's aren't handled in client's headObject/getObject calls

### ISSUE THREAD

**Issue by stiost** [awslabs/aws-sdk-kotlin#444]
## Describe the bug
When specifying IfNoneMatch on a request the call fails with an UnknownServiceErrorException which is awkward to handle

## Expected Behavior
Return a response with a status code of not modified (or throw a more reasonable Exception)

## Current Behavior
Throws UnknownServiceErrorException: failed to parse response as restXml error

```
Exception in thread "main" aws.sdk.kotlin.runtime.UnknownServiceErrorException: failed to parse response as restXml error
	at aws.sdk.kotlin.services.s3.transform.GetObjectOperationDeserializerKt.throwGetObjectError(GetObjectOperationDeserializer.kt:97)
	at aws.sdk.kotlin.services.s3.transform.GetObjectOperationDeserializerKt.access$throwGetObjectError(GetObjectOperationDeserializer.kt:1)
	at aws.sdk.kotlin.services.s3.transform.GetObjectOperationDeserializer.deserialize(GetObjectOperationDeserializer.kt:32)
	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)
	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)
	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:153)
	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler$call$1.invokeSuspend(SdkOperationExecution.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:513)
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.completeResumeReceive(AbstractChannel.kt:907)
	at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:83)
	at kotlinx.coroutines.channels.AbstractSendChannel.trySend-JP2dKIU(AbstractChannel.kt:154)
	at aws.sdk.kotlin.runtime.http.engine.crt.SdkStreamResponseHandler.signalResponse(SdkStreamResponseHandler.kt:107)
	at aws.sdk.kotlin.runtime.http.engine.crt.SdkStreamResponseHandler.onResponseHeadersDone(SdkStreamResponseHandler.kt:114)
	at aws.sdk.kotlin.crt.http.HttpRequestUtilKt$asJniStreamResponseHandler$1.onResponseHeadersDone(HttpRequestUtil.kt:47)
	at software.amazon.awssdk.crt.http.HttpStreamResponseHandlerNativeAdapter.onResponseHeadersDone(HttpStreamResponseHandlerNativeAdapter.java:23)
Caused by: java.lang.IllegalStateException: unable to parse error from empty response
	at aws.sdk.kotlin.services.s3.transform.GetObjectOperationDeserializerKt.throwGetObjectError(GetObjectOperationDeserializer.kt:93)
	... 21 more

```

## Steps to Reproduce

```
    val putObjectResponse = s3client.putObject {
        this.bucket = bucketName
        this.key = key
        this.body = Paths.get(fileName).asByteStream()
    }

    val getObjectRequest = GetObjectRequest {
        this.bucket = bucketName
        this.key = key
        this.ifNoneMatch = putObjectResponse.eTag
    }

    s3client.getObject(getObjectRequest) { response ->
        println(response.eTag)
        println("has body: ${response.body != null}")
    }
```

## Possible Solution
An exception feels unnecessary as not modified is an expected response if specifying IfNoneModified, some sort of status code on the response object would probably be simplest.

## Your Environment

* AWS Kotlin SDK version used: 0.9.3-alpha
* Platform (JVM/JS/Native): JVM
* Operating System and version: Linux 5.14.16

**Comment by ianbotsf** [comment]
Thanks @stiost for the bug report. This appears to be a variant of #256. Running some quick tests to verify.

**Comment by ianbotsf** [comment]
Upon further investigation, while #256 is another example of an unknown service response (301 vs 304), _this_ issue is slightly different in that (as mentioned above) 304 is an expected response from the service according to [the `GetObject` documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html). It's worth examining how this should be handled by the SDK in a more graceful manner.

Adding a status code on the response object is technically possible but may not be optimal since a response object indicates a normal (i.e., HTTP 200) result from the service. If we received 304 from the service, we'd still have to populate values for the rest of the response object fields as though it were a normal response. This would be inconsistent with other response objects and may be confusing.

This may be best modeled as an exception, albeit one that is more specific than the current `UnknownServiceErrorException`. This could be an `S3Exception` or possibly even a new `NotModifiedException`.

As a short-term workaround, the status code is available in the currently-thrown exception. You should be able to detect and handle the 304 case like so:

```kotlin
try {
    s3client.getObject(getObjectRequest) { response ->
        println(response.eTag)
        println("has body: ${response.body != null}")
    }
} catch (e: AwsServiceException) {
    val httpResponse = e.sdkErrorMetadata.protocolResponse as? HttpResponse
    when (httpResponse?.status) {
        HttpStatusCode.NotModified -> println("S3 returned HTTP 304: Not modified")
        else -> println("Got exception $e")
    }
}
```

**Comment by stiost** [comment]
Thank you for looking into this! As this is currently alpha I assume API changes are allowed? The project lead of Kotlin has a great blog post here https://elizarov.medium.com/kotlin-and-exceptions-8062f589d07 about how they envisioned using exceptions vs sealed classes as return values in APIs.

Maybe something like this:

```
        val request = GetObjectRequest {
            bucket = ""
            key = ""
        }

        s3Client.getObject(request) { response ->
            when (response) {
                is GetObjectResponse -> {
   
                }
                is NotFoundResponse -> {

                }
                is NotModifiedResponse -> {

                }
            }
        }
```

With Kotlin 1.6's new warning on unhandled when cases would make the error cases a lot more obvious to the users of the API, though I realise this might be a huge change for the SDK.
