### ISSUE TITLE
S3 requests with prefix/delimiter containing URLEncodable characters will fail signature validation

### ISSUE THREAD

**Issue by krodyrobi** [awslabs/aws-sdk-kotlin#448]
## Describe the bug

S3 requests with prefix/delimiter containing URLEncodable characters will fail signature validation

## Expected Behavior

Expect to be able to use `/` as a delimiter in file object keys, and filter based on a prefix containing the delimiter character.

## Current Behavior

Cases for signature creation:

| delimiter | prefix  | outcome |
|-----------|---------|---------|
| null      | null    | OK      |
| /         | null    | FAIL    |
| /         | folder  | FAIL    |
| /         | folder/ | FAIL    |
| -         | folder  | OK      |
| -         | folder- | OK      |

Seems like characters in either delimiter or prefix that are URLEncodable will fail generating correct signatures.
Java sdk2 seems to run just fine with `/`

```txt
112:23:46.281 TRACE a.s.k.r.h.operation.SerializeHandler sdkRequestId: d8e6e856-acc8-4492-91d7-badc7bc8b9ba; service: S3; operation: ListObjects; - request serialized in 9.423961ms
12:23:46.289 DEBUG ResolveAwsEndpoint                   sdkRequestId: d8e6e856-acc8-4492-91d7-badc7bc8b9ba; service: S3; operation: ListObjects; - resolved endpoint: AwsEndpoint(endpoint=Endpoint(uri=https://s3.eu-central-1.amazonaws.com, isHostnameImmutable=false), credentialScope=CredentialScope(region=eu-central-1, service=null))
12:23:46.353 DEBUG httpTraceMiddleware                  sdkRequestId: d8e6e856-acc8-4492-91d7-badc7bc8b9ba; service: S3; operation: ListObjects; - HttpRequest:
GET /BUCKETNAME?delimiter=%252F&max-keys=1
Host: s3.eu-central-1.amazonaws.com
User-Agent: aws-sdk-kotlin/0.9.3-alpha api/s3/0.9.3-alpha os/macos/11.6 lang/kotlin/1.5.31 md/javaVersion/11.0.10 md/jvmName/OpenJDK_64-Bit_Server_VM md/jvmVersion/11.0.10+9-LTS-sapmachine
x-amz-user-agent: aws-sdk-kotlin/0.9.3-alpha
X-Amz-Date: 20211126T102346Z
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: [REDACTED], SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-user-agent, Signature=aedd959fec02fffe947a7bb37d45d00b744da0777bc909af3b9eef64c751148b

Exception in thread "main" aws.sdk.kotlin.services.s3.model.S3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.
at aws.sdk.kotlin.services.s3.transform.ListObjectsOperationDeserializerKt.throwListObjectsError(ListObjectsOperationDeserializer.kt:136)
at aws.sdk.kotlin.services.s3.transform.ListObjectsOperationDeserializerKt.access$throwListObjectsError(ListObjectsOperationDeserializer.kt:1)
at aws.sdk.kotlin.services.s3.transform.ListObjectsOperationDeserializer.deserialize(ListObjectsOperationDeserializer.kt:42)
at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)
at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)
at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:153)
at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler$call$1.invokeSuspend(SdkOperationExecution.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
at MainKt.main(Main.kt:103)
```

## Steps to Reproduce

```kotlin
val rootLogger: Logger = LoggerFactory.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME) as Logger
rootLogger.level = Level.ALL

val s3Client = S3Client {
    region = "eu-central-1"
    sdkLogMode = SdkLogMode.LogRequestWithBody
}

runBlocking {
    try {
        val listing = s3Client.listObjects {
            this.bucket = "BUCKETNAME"
            maxKeys = 1
            delimiter = "/"
            prefix = null
        }

        val requestContents: List<Object> = listing.contents ?: emptyList()
        requestContents.forEach {
            println("* ${it.key}")
        }
    } catch (ex: AwsServiceException) {
        val httpResp = ex.sdkErrorMetadata.protocolResponse as? HttpResponse
        // Always null
        if (httpResp != null) {
            println(httpResp.headers)
            println(httpResp.body.readAll()?.decodeToString())
        }
        throw ex
    }
}

```
## Possible Solution

Use encoded values when generating the signature.

## Context

Was trying to read s3 objects within a folder hierarchy.

## Your Environment

* AWS Kotlin SDK version used: aws.sdk.kotlin:s3:0.9.3-alpha
* Platform (JVM/JS/Native): JVM
* Operating System and version: MacOS 11.6

**Comment by aajtodd** [comment]
Thanks for the bug report and the detailed table! I've reproduced the bug locally.

The issue appears to be with what happens to the request _after_ signing. 

S3 doesn't use double uri encoding. What happens is the request is signed correctly and then later when finalized to go out on the wire it's getting encoded a second time [here](https://github.com/awslabs/aws-sdk-kotlin/blob/v0.9.3-alpha/aws-runtime/http-client-engine-crt/common/src/aws/sdk/kotlin/runtime/http/engine/crt/RequestUtil.kt#L52)

Specifically the `url.encodedPath` will encode the query parameters a second time (first time is [here](https://github.com/awslabs/aws-sdk-kotlin/blob/v0.9.3-alpha/aws-runtime/crt-util/common/src/aws/sdk/kotlin/runtime/crt/Http.kt#L84) after signing).

I've confirmed this is the issue by modifying the code to _not_ encode query parameters when forming the encoded path:
```kotlin
    val cp = url.copy(encodeParameters = false)
    return aws.sdk.kotlin.crt.http.HttpRequest(method.name, cp.encodedPath, crtHeaders.build(), bodyStream)
```

This bug is also present in the `KtorEngine` but there it happens because ktor client will encode the parameters internally themselves by default. (NOTE: Parameters are copied over [here](https://github.com/awslabs/smithy-kotlin/blob/v0.7.2-alpha/runtime/protocol/http-client-engines/http-client-engine-ktor/jvm/src/aws/smithy/kotlin/runtime/http/engine/ktor/KtorUtils.kt#L37) in the ktor engine, they are encoded later internally a second time after this).

The issue about `httpResp` always being null is a separate bug, see #449 for more detail if you're curious.

We will take a look at getting a fix out.
