### ISSUE TITLE
SendCountExceedException when accessing S3 bucket in another region via Ktor client

### ISSUE THREAD

**Issue by ianbotsf** [awslabs/aws-sdk-kotlin#527]
### Describe the bug

When attempting to read from an S3 bucket hosted in a different region than the client configuration using the Ktor client engine, the following error is observed:

`io.ktor.client.features.SendCountExceedException: Max send count 20 exceeded. Consider increasing the property maxSendCount if more is required.`

This error is unintuitive and does not correctly indicate the problem or any possible resolutions.

### Expected behavior

The API call should throw a clearer error indicating the problem (missing endpoint configuration and/or incorrect region).

### Current behavior

The following error is thrown:

```
Exception in thread "main" io.ktor.client.features.SendCountExceedException: Max send count 20 exceeded. Consider increasing the property maxSendCount if more is required.
	at io.ktor.client.features.HttpSend$DefaultSender.execute(HttpSend.kt:121)
	at io.ktor.client.features.HttpRedirect$Feature.handleCall(HttpRedirect.kt:95)
	at io.ktor.client.features.HttpRedirect$Feature.access$handleCall(HttpRedirect.kt:47)
	at io.ktor.client.features.HttpRedirect$Feature$handleCall$1.invokeSuspend(HttpRedirect.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### Steps to Reproduce

```kotlin
suspend fun main() {
    val globalConfig = AwsClientConfig.fromEnvironment { }
    val s3 = S3Client(globalConfig) {
        httpClientEngine = KtorEngine()
    }
    s3.getObject(GetObjectRequest {
        bucket = "aws-sdk-kotlin-api-docs" // Bucket hosted in another region
        key = "foo"
    }) { }
}
```

### Context

[Originally noted](https://github.com/awslabs/aws-sdk-kotlin/issues/525#issuecomment-1035451383) in #525.

### AWS Kotlin SDK version used

0.12.0-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Amazon Linux 2

**Comment by ianbotsf** [comment]
PR in [**smithy-kotlin#590**](https://github.com/awslabs/smithy-kotlin/pull/590).

**Comment by ianbotsf** [comment]
PR approved and pushed to `smithy-kotlin/main`. This fix will be in the next SDK release.
