### ISSUE TITLE
Completemultipart upload request fails with runtime exception

### ISSUE THREAD

**Issue by sdhuka** [awslabs/aws-sdk-kotlin#536]
### Describe the bug

completeMultipartUpload api fails with Runtime exception:

### Expected behavior

No exceptions should be observed.

### Current behavior

completeMultipartUpload fails with following error while serializing the list of completed parts.
```
2022-02-20 17:40:03.150 20699-20952/com.example.storage_sample_new W/System.err: java.lang.RuntimeException: Unsupported Property:null
2022-02-20 17:40:03.152 20699-20952/com.example.storage_sample_new W/System.err:     at com.android.org.kxml2.io.KXmlSerializer.setProperty(KXmlSerializer.java:305)
2022-02-20 17:40:03.154 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.serde.xml.XmlPullSerializer.<init>(XmlStreamWriterXmlPull.kt:25)
2022-02-20 17:40:03.156 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.serde.xml.XmlPullSerializer.<init>(XmlStreamWriterXmlPull.kt:13)
2022-02-20 17:40:03.158 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.serde.xml.XmlStreamWriterXmlPullKt.xmlStreamWriter(XmlStreamWriterXmlPull.kt:89)
2022-02-20 17:40:03.161 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.serde.xml.XmlStreamWriterXmlPullKt.xmlStreamWriter$default(XmlStreamWriterXmlPull.kt:89)
2022-02-20 17:40:03.162 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.serde.xml.XmlSerializer.<init>(XmlSerializer.kt:17)
2022-02-20 17:40:03.165 20699-20952/com.example.storage_sample_new W/System.err:     at aws.sdk.kotlin.services.s3.transform.CompletedMultipartUploadPayloadSerializerKt.serializeCompletedMultipartUploadPayloadWithXmlNameCompleteMultipartUpload(CompletedMultipartUploadPayloadSerializer.kt:27)
2022-02-20 17:40:03.168 20699-20952/com.example.storage_sample_new W/System.err:     at aws.sdk.kotlin.services.s3.transform.CompleteMultipartUploadOperationSerializer.serialize(CompleteMultipartUploadOperationSerializer.kt:43)
2022-02-20 17:40:03.170 20699-20952/com.example.storage_sample_new W/System.err:     at aws.sdk.kotlin.services.s3.transform.CompleteMultipartUploadOperationSerializer.serialize(CompleteMultipartUploadOperationSerializer.kt:20)
2022-02-20 17:40:03.172 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$2.invoke(SdkOperationExecution.kt:93)
2022-02-20 17:40:03.173 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$2.invoke(SdkOperationExecution.kt:93)
2022-02-20 17:40:03.175 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.http.operation.SerializeHandler.call(SdkOperationExecution.kt:120)
2022-02-20 17:40:03.176 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.http.operation.SerializeHandler.call(SdkOperationExecution.kt:107)
2022-02-20 17:40:03.178 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.http.operation.InitializeHandler.call(SdkOperationExecution.kt:104)
2022-02-20 17:40:03.179 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.io.middleware.Phase.handle(Phase.kt:60)
2022-02-20 17:40:03.180 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
2022-02-20 17:40:03.182 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.http.operation.SdkHttpOperationKt.execute(SdkHttpOperation.kt:83)
2022-02-20 17:40:03.183 20699-20952/com.example.storage_sample_new W/System.err:     at aws.smithy.kotlin.runtime.http.operation.SdkHttpOperationKt.roundTrip(SdkHttpOperation.kt:66)
2022-02-20 17:40:03.185 20699-20952/com.example.storage_sample_new W/System.err:     at aws.sdk.kotlin.services.s3.DefaultS3Client.completeMultipartUpload(DefaultS3Client.kt:160)
2022-02-20 17:40:03.186 20699-20952/com.example.storage_sample_new W/System.err:     at aws.sdk.kotlin.services.s3.S3Client$DefaultImpls.completeMultipartUpload(S3Client.kt:258)
2022-02-20 17:40:03.188 20699-20952/com.example.storage_sample_new W/System.err:     at aws.sdk.kotlin.services.s3.DefaultS3Client.completeMultipartUpload(DefaultS3Client.kt:34)
2022-02-20 17:40:03.189 20699-20952/com.example.storage_sample_new W/System.err:     at com.amplifyframework.storage.s3.transfer.worker.CompleteMultiPartUploadWorker.performWork(CompleteMultiPartUploadWorker.kt:43)
2022-02-20 17:40:03.191 20699-20952/com.example.storage_sample_new W/System.err:     at com.amplifyframework.storage.s3.transfer.worker.BaseTransferWorker.doWork$suspendImpl(BaseTransferWorker.kt:86)
2022-02-20 17:40:03.192 20699-20952/com.example.storage_sample_new W/System.err:     at com.amplifyframework.storage.s3.transfer.worker.BaseTransferWorker.doWork(Unknown Source:0)
2022-02-20 17:40:03.193 20699-20952/com.example.storage_sample_new W/System.err:     at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:68)
2022-02-20 17:40:03.194 20699-20952/com.example.storage_sample_new W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

```

### Steps to Reproduce

val completedParts = LIST_OF_PART_ETAGS
s3.completeMultipartUpload {
    bucket = BUCKET_NAME
    key = KEY
    multipartUpload = CompletedMultipartUpload {
        parts = completedParts
    }
    uploadId = UPLOAD_ID
}

### AWS Kotlin SDK version used

0.12.0-beta

### Platform (JVM/JS/Native)

Native

### Operating System and version

Android 31

**Comment by aajtodd** [comment]
Looks like it's related to unsupported XML pull stream writer [properties](https://github.com/awslabs/smithy-kotlin/blob/v0.7.8/runtime/serde/serde-xml/jvm/src/aws/smithy/kotlin/runtime/serde/xml/XmlStreamWriterXmlPull.kt#L25)

**Comment by aajtodd** [comment]
I've reproduced this on Android. It works fine on desktop.

We have plans to overhaul XML a bit anyway so we are going to bump that in priority rather than try and track down the differences between the `XmlPull` implementations between Android and desktop. This will take a bit of time to complete (couple weeks) so we ask for patience.
