### ISSUE TITLE
AWS CRT lib fails during S3 object uploads on Apple M1

### ISSUE THREAD

**Issue by inktomi** [awslabs/aws-sdk-kotlin#562]
### Describe the bug

Trying the sample code provided for uploading objects to S3 fails on laptops with Apple M1 processors. 

### Expected behavior

Sample code should work. 

### Current behavior

```
Unable to unpack AWS CRT lib: java.io.IOException: Unable to open library in jar for AWS CRT: /osx/armv8/libaws-crt-jni.dylib
java.io.IOException: Unable to open library in jar for AWS CRT: /osx/armv8/libaws-crt-jni.dylib
	at software.amazon.awssdk.crt.CRT.extractAndLoadLibrary(CRT.java:158)
	at software.amazon.awssdk.crt.CRT.loadLibraryFromJar(CRT.java:223)
	at software.amazon.awssdk.crt.CRT.<clinit>(CRT.java:33)
	at software.amazon.awssdk.crt.CrtResource.<clinit>(CrtResource.java:100)
	at aws.sdk.kotlin.crt.io.EventLoopGroup.<init>(EventLoopGroupJVM.kt:22)
	at aws.sdk.kotlin.runtime.crt.SdkDefaultIO$EventLoop$2.invoke(SdkDefaultIO.kt:24)
	at aws.sdk.kotlin.runtime.crt.SdkDefaultIO$EventLoop$2.invoke(SdkDefaultIO.kt:22)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at aws.sdk.kotlin.runtime.crt.SdkDefaultIO.getEventLoop(SdkDefaultIO.kt:22)
	at aws.sdk.kotlin.runtime.crt.SdkDefaultIO$ClientBootstrap$2.invoke(SdkDefaultIO.kt:38)
	at aws.sdk.kotlin.runtime.crt.SdkDefaultIO$ClientBootstrap$2.invoke(SdkDefaultIO.kt:37)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at aws.sdk.kotlin.runtime.crt.SdkDefaultIO.getClientBootstrap(SdkDefaultIO.kt:37)
	at aws.sdk.kotlin.runtime.http.engine.crt.CrtHttpEngine.<init>(CrtHttpEngine.kt:56)
	at aws.sdk.kotlin.runtime.http.engine.crt.CrtHttpEngine.<init>(CrtHttpEngine.kt:32)
	at aws.sdk.kotlin.services.s3.DefaultS3Client.<init>(DefaultS3Client.kt:37)
	at aws.sdk.kotlin.services.s3.S3Client$Companion.invoke(S3Client.kt:45)
	at aws.sdk.kotlin.services.s3.S3Client$Companion.invoke$default(S3Client.kt:40)
```

### Steps to Reproduce

Run Amazon S3 sample code to upload an object. 

### AWS Kotlin SDK version used

0.9.4-beta

### Platform (JVM/JS/Native)

JVM 11

### Operating System and version

macOS 12.3

**Comment by ianbotsf** [comment]
Hi @inktomi, thanks for the bug report. This issue is already documented in #473 so resolving this one as a duplicate. Feel free to 👍 the other issue and track its progress there.
