### ISSUE TITLE
How to avoid unexpected end of stream errors?

### ISSUE THREAD

**Issue by AlexandreBrown** [awslabs/aws-sdk-kotlin#599]
### Describe the issue

When performing a lot of requests in a highly concurrent environment we sometimes get the following error : 
```
java.io.IOException: unexpected end of stream on https://s3.us-east-2.amazonaws.com/
```
We have a lot of coroutines that can send data to s3 concurrently and they all use the same `aws.sdk.kotlin.services.s3.S3Client` instance for performance reasons and the connection is not closed after a request because otherwise the other requests would not work.  
  
I saw on [this post](https://github.com/square/okhttp/issues/5021) that a workaround is to add a header `.header("Connection", "close")`.  
  
Is it possible to add this header using the AWS sdk? Or is there a way to avoid this error?  
Sometimes we can send 10 000 requests without any issue, sometimes a few of them fail with the stacktrace I posted.  

Thanks

### Steps to Reproduce

1. Create 30+ coroutines that send PUT requests to S3 in a loop for a prolonged period of time (20 min+).
2. Notice the exception

### Current behavior

```kotlin
11:02:51.212 [DefaultDispatcher-worker-10] ERROR aws.smithy.kotlin.runtime.http.engine.ktor.KtorEngine - throwing
java.io.IOException: unexpected end of stream on https://s3.us-east-2.amazonaws.com/...
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	... 16 common frames omitted
11:02:51.214 [DefaultDispatcher-worker-10] DEBUG Retry - sdkRequestId: 23b27b9e-d630-4e3f-af6b-ec0e08ddd764; service: S3; operation: PutObject; - request failed with non-retryable error
11:02:51.215 [DefaultDispatcher-worker-20] ERROR aws.smithy.kotlin.runtime.http.engine.ktor.KtorEngine - throwing
java.util.concurrent.CancellationException: Parent job is Cancelling
	at aws.smithy.kotlin.runtime.http.engine.CoroutineUtilsKt$attachToOuterJob$cleanupHandler$1.invoke(CoroutineUtils.kt:39)
	at aws.smithy.kotlin.runtime.http.engine.CoroutineUtilsKt$attachToOuterJob$cleanupHandler$1.invoke(CoroutineUtils.kt:37)
	at kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1457)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1499)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1465)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1499)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.childCancelled(JobSupport.kt:651)
	at kotlinx.coroutines.ChildHandleNode.childCancelled(JobSupport.kt:1466)
	at kotlinx.coroutines.JobSupport.cancelParent(JobSupport.kt:358)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:332)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:900)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:147)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Exception in thread "main" java.io.IOException: unexpected end of stream on https://s3.us-east-2.amazonaws.com/...
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	... 16 more
```

### AWS Kotlin SDK version used

0.14.2-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Ubuntu 20.04.3 LTS

**Comment by aajtodd** [comment]
@AlexandreBrown Thanks for the report. This looks like a bug to me.

Anything more you can share about the operation in question? What size upload? Any additional debug/trace logs you may have gathered and can share?

I'll see if we can't reproduce it and update here when I have more to share.

**Comment by AlexandreBrown** [comment]
Hi @aajtodd , the upload size is very small, it is images (PNG) that are ~2kb in size but a lot of them can be sent.  
Each request 1 image is sent, there can be multiple requests concurrently.  
  
It's hard to reproduce, today we did multiple tests of various dataset size (10k images, 2k images, 500 images, 50 images), I saw no errors but yesterday during a 10k test, a few S3 requests failed with the logs I posted.  
  
Here is part of the logs when the test got a few requests failed if that helps (the failed requests is at the end of the logs) :  
[logs1.txt](https://github.com/awslabs/aws-sdk-kotlin/files/8605414/logs1.txt)

**Comment by aajtodd** [comment]
I've looked at this a bit.

My initial investigation took me to this [okhttp issue](https://github.com/square/okhttp/issues/5390) which links to this [ktor issue](https://github.com/ktorio/ktor/issues/1708#issuecomment-609988128) as the culprit.

That issue suggests that it was happening because `retryOnConnectionFailure` was set to `false`. This was resolved over a year ago [in ktor](https://github.com/ktorio/ktor/pull/2460) though and I have verified that this setting is getting set to `true`.

I have not otherwise been able to recreate this. Our next short term step here is going to be to enable additional logging that may help understand what is going on. This will be available hopefully in the next release and I'll update this ticket with instructions.

----------

Slightly longer term we are looking to remove `ktor` and bind directly to `okhttp` as well us upgrade to `ktor-2.x` (which we still use for byte channel abstractions internally). I don't expect either of these to fix the issue per say but making those changes will undoubtedly have potential to cause subtle changes in how requests are executed. This is more of an FYI than anything.

**Comment by AlexandreBrown** [comment]
Closing this until I can reproduce again.

**Comment by aajtodd** [comment]
@mgroth0 Indeed it seems to be. Will respond in the other issue.
