### ISSUE TITLE
Polly e2e test fails

### ISSUE THREAD

**Issue by ianbotsf** [awslabs/aws-sdk-kotlin#611]
### Describe the bug

The [Polly end-to-end test](https://github.com/awslabs/aws-sdk-kotlin/blob/main/services/polly/e2eTest/PollyPresignerTest.kt) currently fails.

### Expected behavior

It is expected that the test should complete successfully.

### Current behavior

The test fails with the following error:

```
> Task :services:polly:e2eTest

PollyPresignerTest > clientBasedPresign() STANDARD_ERROR
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

PollyPresignerTest > clientBasedPresign() FAILED
    software.amazon.awssdk.crt.CrtRuntimeException: HttpClientConnection.MakeRequest: Unable to Execute Request (aws_last_error: AWS_ERROR_HTTP_INVALID_PATH(2054), Path is invalid.) AWS_ERROR_HTTP_INVALID_PATH(2054)
        at software.amazon.awssdk.crt.http.HttpClientConnection.httpClientConnectionMakeRequest(Native Method)
        at software.amazon.awssdk.crt.http.HttpClientConnection.makeRequest(HttpClientConnection.java:45)
        at aws.sdk.kotlin.crt.http.HttpClientConnectionJVM.makeRequest(HttpClientConnectionJVM.kt:16)
        at aws.smithy.kotlin.runtime.http.engine.crt.CrtHttpEngine.roundTrip(CrtHttpEngine.kt:95)
        at aws.smithy.kotlin.runtime.http.engine.crt.CrtHttpEngine$roundTrip$1.invokeSuspend(CrtHttpEngine.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at aws.sdk.kotlin.services.polly.PollyPresignerTest.clientBasedPresign(PollyPresignerTest.kt:23)
```

### Steps to Reproduce

Bootstrap the Polly client and attempt to run the end-to-end test:

```sh
./gradlew :codegen:sdk:bootstrap -Paws.services=+polly
./gradlew :services:polly:e2eTest
```

### Context

This was discovered while refactoring service clients to support KMP (#610). It is unknown for how long the test has been broken.

### AWS Kotlin SDK version used

0.15.3-SNAPSHOT

### Platform (JVM/JS/Native)

JVM, OpenJDK 1.8.0_312

### Operating System and version

Amazon Linux 2

**Comment by ianbotsf** [comment]
I cannot reproduce this anymore on the latest versions of CRT, **smithy-kotlin**, and **aws-sdk-kotlin**. I went back and checked out the old refs from my #610 PR and re-verified the problem _did_ happen then. So some change(s) in the meantime must have fixed this.

Resolving as fixed.
