### ISSUE TITLE
S3 e2e test fails with new signer

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-sdk-kotlin#619]
### Describe the bug

After merging the new signer implementation (https://github.com/awslabs/aws-sdk-kotlin/pull/616) the `S3BucketOpsIntegrationTest::testQueryParameterEncoding` e2e test fails.

### Expected behavior

Test passes

### Current behavior

```
S3BucketOpsIntegrationTest > testQueryParameterEncoding() FAILED                                                                                                       
    java.lang.NumberFormatException: For input string: "&'"                        
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:638)                  
        at aws.smithy.kotlin.runtime.util.text.TextKt.urlDecodeComponent(Text.kt:194)                                                    
        at aws.smithy.kotlin.runtime.util.text.TextKt.urlReencodeComponent(Text.kt:217)                                                                                
        at aws.smithy.kotlin.runtime.util.text.TextKt.urlReencodeComponent$default(Text.kt:216)  
        at aws.smithy.kotlin.runtime.auth.awssigning.CanonicalizerKt.asQueryParamComponents(Canonicalizer.kt:194)                                                      
        at aws.smithy.kotlin.runtime.auth.awssigning.CanonicalizerKt.canonicalQueryParams(Canonicalizer.kt:189)                                                        
        at aws.smithy.kotlin.runtime.auth.awssigning.CanonicalizerKt.access$canonicalQueryParams(Canonicalizer.kt:1)                                                   
        at aws.smithy.kotlin.runtime.auth.awssigning.DefaultCanonicalizer.canonicalRequest(Canonicalizer.kt:121)                                                      
        at aws.smithy.kotlin.runtime.auth.awssigning.DefaultAwsSignerImpl.sign(DefaultAwsSigner.kt:28)                                                                 
        at aws.smithy.kotlin.runtime.auth.awssigning.DefaultAwsSignerImpl$sign$1.invokeSuspend(DefaultAwsSigner.kt)                                                   
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                                                      
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)                                                                                                
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)                                                      
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)                                                                                           
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)                                                                                       
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)                                                                                                   
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)                                                                              
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)       
        at aws.sdk.kotlin.e2etest.S3BucketOpsIntegrationTest.testQueryParameterEncoding(S3IntegrationTest.kt:105)        
```

### Steps to Reproduce

```
./gradlew :codegen:sdk:bootstrap -Paws.services=+s3
./gradlew :services:s3:e2eTest
```

### AWS Kotlin SDK version used

main@c40eaac6cb3e33c6c1edb91033513b2221baa06e

### Platform (JVM/JS/Native)

JVM

### Operating System and version

macos

**Comment by ianbotsf** [comment]
Resolved by [smithy-kotlin#654](https://github.com/awslabs/smithy-kotlin/pull/654).
