### ISSUE TITLE
CredentialsProviderChain unable to load credentials on EKS

### ISSUE THREAD

**Issue by vgiguere** [awslabs/aws-sdk-kotlin#627]
### Describe the bug

When loading a Spring application on an AWS EKS cluster (which is able load apps credentials through the **Java** SDK), the **Kotlin** SDK's CredentialsProviderChain fails to load them through it's chain.

```
No credentials could be loaded from the chain: CredentialsProviderChain -> EnvironmentCredentialsProvider -> ProfileCredentialsProvider -> StsWebIdentityProvider -> EcsCredentialsProvider -> ImdsCredentialsProvider
```

### Expected behavior

I would expect the **Kotlin** SDK to be able to fetch the same credentials that the **Java** SDK is able to load

### Current behavior

I have instrumented my Spring Configuration file to log some information to help.

This is the Spring Configuration file:

```
@Configuration
class DynamoDBConfig(private val logger: Logger = LoggerFactory.getLogger(DynamoDBConfig::class.java)) {

    @Bean
    fun amazonDynamoDB(): DynamoDbClient = runBlocking {
        DynamoDbClient.fromEnvironment().apply {
            debug()
        }
    }

    private suspend fun debug() {
        kotlin.runCatching {
            logger.info("Java SDK Credential Provider Chain - Initializing")
            DefaultAWSCredentialsProviderChain.getInstance().let {
                logger.info("Java SDK Credential Provider Chain - Getting Credentials from ProviderChain")
                logger.info("Java SDK Credential Provider Chain - Credentials: ${it.credentials}")
            }
        }.onFailure { ex -> logger.error("Java SDK Credential Provider Chain - Exception", ex) }

        kotlin.runCatching {
            logger.info("Kotlin SDK Credential Provider Chain - Initializing")
            DefaultChainCredentialsProvider().let {
                logger.info("Kotlin SDK  Credential Provider Chain - Getting Credentials from ProviderChain")
                logger.info("Kotlin SDK  Credential Provider Chain - Credentials: ${it.getCredentials()}")
            }
        }.onFailure { ex -> logger.error("Kotlin SDK Credential Provider Chain - Exception", ex) }
    }
}
```

These are the logs (I have timestamps and log level stuff to make it more readable

The logs from the **Java** `CredentialsProviderChain`
```
DynamoDBConfig message=Java SDK Credential Provider Chain - Initializing
DynamoDBConfig message=Java SDK Credential Provider Chain - Getting Credentials from ProviderChain
com.amazonaws.auth.AWSCredentialsProviderChain message=Unable to load credentials from EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
com.amazonaws.auth.AWSCredentialsProviderChain message=Unable to load credentials from SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey)
com.amazonaws.auth.AWSCredentialsProviderChain message=Unable to load credentials from WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName
com.amazonaws.auth.AWSCredentialsProviderChain message=Unable to load credentials from com.amazonaws.auth.profile.ProfileCredentialsProvider@404ced67: profile file cannot be null
com.amazonaws.auth.AWSCredentialsProviderChain message=Loading credentials from com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@71531dd7
DynamoDBConfig message=Java SDK Credential Provider Chain - Credentials: com.amazonaws.auth.BasicSessionCredentials@20256a0b

```

The logs from the **Kotlin** `CredentialsProviderChain`
```
DynamoDBConfig message=Kotlin SDK Credential Provider Chain - Initializing
DynamoDBConfig message=Kotlin SDK  Credential Provider Chain - Getting Credentials from ProviderChain
aws.sdk.kotlin.runtime.auth.credentials.CredentialsProviderChain message=unable to load credentials from aws.sdk.kotlin.runtime.auth.credentials.EnvironmentCredentialsProvider@79ca7bea: Missing value for environment variable `AWS_ACCESS_KEY_ID`
aws.sdk.kotlin.runtime.auth.credentials.ProfileCredentialsProvider message=Loading credentials from profile `default`
aws.sdk.kotlin.runtime.auth.credentials.CredentialsProviderChain message=unable to load credentials from aws.sdk.kotlin.runtime.auth.credentials.ProfileCredentialsProvider@3869a6e5: could not find source profile default
aws.sdk.kotlin.runtime.auth.credentials.CredentialsProviderChain message=unable to load credentials from aws.sdk.kotlin.runtime.auth.credentials.StsWebIdentityProvider@d25e878: Required field `roleArn` could not be automatically inferred for StsWebIdentityCredentialsProvider. Either explicitly pass a value, set the environment variable `AWS_ROLE_ARN`, or set the JVM system property `aws.roleArn`
aws.sdk.kotlin.runtime.auth.credentials.CredentialsProviderChain message=unable to load credentials from aws.sdk.kotlin.runtime.auth.credentials.EcsCredentialsProvider@578c3fd9: Container credentials URI not set
aws.sdk.kotlin.runtime.auth.credentials.CredentialsProviderChain message=unable to load credentials from aws.sdk.kotlin.runtime.auth.credentials.ImdsCredentialsProvider@49491770: failed to load instance profile
DynamoDBConfig message=Kotlin SDK Credential Provider Chain - Exception exception=aws.sdk.kotlin.runtime.auth.credentials.CredentialsProviderException: No credentials could be loaded from the chain: CredentialsProviderChain -> EnvironmentCredentialsProvider -> ProfileCredentialsProvider -> StsWebIdentityProvider -> EcsCredentialsProvider -> ImdsCredentialsProvider
```

### Steps to Reproduce

Try to get Credentials from an application running on an EKS Cluster on which the Java SDK is able to load IAM profiles etc.

### Possible Solution

It looks like the Kotlin SDK is missing a `EC2ContainerCredentialsProvider` maybe?

### Context

I am ready to try a new DynamoDB persistence to replace a 5TB relational database that is out of whack. It's a mission critical system where I work and this is blocking us.

If you could provide workarounds in the interim ?

I was thinking of using the `ProfileCredentialsProvider` and try to load the IAM profile of our app where all the required policies are defined (not sure if it will work)

Otherwise, I'll try to get access keys, but this goes against my employer's security guidelines... 

### AWS Kotlin SDK version used

0.15.0, 0.16.0, 0.16.1-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Docker, Java 11.0.14.1

**Comment by lucix-aws** [comment]
Thanks for reporting.

To clarify, the `ImdsCredentialsProvider` you see in our chain is the Kotlin SDK's version of Java's `EC2ContainerCredentialsProvider`. The [header comment](https://github.com/awslabs/aws-sdk-kotlin/blob/7bc65bf9780dd3995ecec5c8d95c8defe4a0b640/aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt) on that class provides a bit of background on how it fetches credentials (not that we expect users to find and read it, just providing here for context). From preliminary investigation, it looks like the root of the failure starts at the exception that's caught [right here](https://github.com/awslabs/aws-sdk-kotlin/blob/7bc65bf9780dd3995ecec5c8d95c8defe4a0b640/aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt#L94).

That said, I'd say your intuition is correct that the Kotlin version should be able to find the credentials that the Java one can.

A few questions here:
1. Are your instances using IMDSv2? That's the only version the provider supports.
2. Would you be able to provide a full stack trace? That should include the message of the underlying exception that I pointed to above, which _should_ tell us more about what exactly is failing.
3. Is your application running in a container, or directly on the instance?

In the meantime, I'm going to try to reproduce this to the best of my ability.

**Comment by vgiguere** [comment]
FYI, I have also tried to delegate to the Java SDK Credentials Provider Chain: 

```
 @Bean
    fun amazonDynamoDB(): DynamoDbClient = runBlocking {
        DynamoDbClient.fromEnvironment {
            region = "us-west-2"
            credentialsProvider = CustomCredentialsProviderChain(DefaultAWSCredentialsProviderChain.getInstance())
        }
    }
    
    ....
    
class CustomCredentialsProviderChain(
    private val javaSDKCredentialsProviderChain: AWSCredentialsProviderChain,
) : CredentialsProvider {

    override suspend fun getCredentials(): KotlinSDKCredentials =
        javaSDKCredentialsProviderChain.credentials.run {
            KotlinSDKCredentials(
                accessKeyId = awsAccessKeyId,
                secretAccessKey = awsSecretKey
            )
        }
}
    
    
```

And I get this error unfortunately - not sure why it would be invalid (I assume the accessKeyId and secretKey would be the same in Java/Kotlin)

```
com.expediagroup.api.trips.persistence.trips.dynamo.DynamoDBPersistenceOperations message=The security token included in the request is invalid. exception=aws.sdk.kotlin.services.dynamodb.model.DynamoDbException: The security token included in the request is invalid.
	at aws.sdk.kotlin.services.dynamodb.transform.GetItemOperationDeserializerKt.throwGetItemError(GetItemOperationDeserializer.kt:66) ~[dynamodb-jvm-0.16.0.jar!/:?]
	at aws.sdk.kotlin.services.dynamodb.transform.GetItemOperationDeserializerKt.access$throwGetItemError(GetItemOperationDeserializer.kt:1) ~[dynamodb-jvm-0.16.0.jar!/:?]
	at aws.sdk.kotlin.services.dynamodb.transform.GetItemOperationDeserializer.deserialize(GetItemOperationDeserializer.kt:36) ~[dynamodb-jvm-0.16.0.jar!/:?]
	```

**Comment by lucix-aws** [comment]
Thanks for the stack trace - we can see the underlying exception there:
`EC2MetadataError: Request forbidden: IMDS is disabled or the caller has insufficient permissions.`

While I try to figure out exactly what's happening here, in the interest of trying to unblock you, I believe you're missing the session token when pulling in the credentials from Java.

**Comment by lucix-aws** [comment]
Reporting back in on this--

At this point, I've recreated every environment in which I imagine you might be running the Kotlin SDK-

* EKS cluster, pod backed by ec2
* EKS cluster, pod backed by fargate
* ECS cluster, task/service backed by ec2
* ECS cluster, task/service backed by fargate

I've been able to load credentials in all of these scenarios.

Ultimately we need to be able to reproduce on our end to root-cause this and identify the proper way forward. To that end, are you able to provide any of the following-

* which (if any, or multiple) of the above combinations I tested that matches what you're running
* the trust policy (with any sensitive information redacted) of the role you expect to be assumed
* any other information you can provide that might help elaborate or potentially expand our search surface on this

**Comment by vgiguere** [comment]
Hi, thanks for your help.

The container is running on an EKS cluster backed by EC2:

Kubernetes version: 1.19
Platform version: eks.10
OS (Architecture): linux (amd64)
OS image: Amazon Linux 2
Container runtime: docker://20.10.13
Kubelet version: v1.19.15-eks-9c63c4
Instance type: r5a.large

The redacted policy on the IAM Role (which loads fine using the Java SDK) contains this: 
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "secretsmanager:*"
            ],
            "Effect": "Allow",
            "Resource": [
                "*"
            ]
        },
        {
            "Action": [
                "s3:List*",
                "s3:Get*"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::redacted/*",
                "arn:aws:s3:::redacted2/-*",
                "arn:aws:s3:::redacted3/-*/*"
            ]
        },
        {
            "Action": [
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:GetItem",
                "dynamodb:Query",
                "dynamodb:UpdateItem",
                "dynamodb:ConditionCheckItem"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:dynamodb:us-west-2:*:table/RedactedTable1",
                "arn:aws:dynamodb:us-west-2:*:table/RedactedTable2"
            ]
        }
    ]
}`


Other info that might be relevant or not: 

The Java SDK is also used in the project > Version: 1.12.232
com.amazonaws:aws-java-sdk-sts:jar:1.12.232
com.amazonaws:aws-java-sdk-eks:jar:1.12.232

We also used this local dynamoDB lib, which I have just realized I had failed to scope to `test` so it's in the class path (but not running):
com.amazonaws:DynamoDBLocal:jar:1.15.0

- Spring Boot 2.6.6
- Kotlin 1.6.10


Also, if it can help, we are a large client of AWS with an Enterprise support plan, so there are a few engineers on your team that we can ping and maybe they can give you access to our stuff or arrange a call where we can show you our code etc. Let me know if you'd like me to try that.

Thanks again.

**Comment by lucix-aws** [comment]
Continuing to dive deep on this-- here's where I'm at:

* I respawned my EKS cluster to match your kubernetes version (not that I expected it to matter, but did so in the interest of getting as close to your configuration as possible). With my sample pod running on an EC2 node, credentials are still resolving for me using the Kotlin SDK via the `ImdsCredentialsProvider`.
* I added a test credential fetch using Java v1. It resolves via the `EC2ContainerCredentialsProviderWrapper`. This provider in Java v1 is actually trying a few different methods of resolving credentials, the final one of which is IMDS ie. what the Kotlin SDK is using. More on that below.
* I added a test fetch using Java v2. It resolves via their `InstanceProfileCredentialsProvider`, which is also using IMDS under the hood.
* I dug into the semantics of IMDS and the two versions it exposes.

Some background on IMDS (instance metadata service) - there are essentially two "versions"
* in v1, the SDKs make a simple GET request to a local host which presents the credentials
* in v2, the SDKs make a PUT to fetch a token, and present that token on a GET which then presents the credentials as in v1
In practice, IMDS should be set up to present credentials for the IAM role that's assigned to the EC2 instance (or in the case of EKS, the node group that would spawn it).

Kotlin only attempts to fetch credentials using the v2 workflow. If we fail to get the token, we will throw an exception and the provider will fail. Java v1, on the other hand, will simply move on from the failure and attempt to GET the credentials as it would for IMDSv1.

Concerning Java v1's `EC2ContainerCredentialsProviderWrapper` - this provider actually has three different code paths that fetch credentials, the final of which is IMDS-based. The first two revolve around checking for the presence of two environment variables
* `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`
* `AWS_CONTAINER_CREDENTIALS_FULL_URI`
If neither are set, the provider then attempts to retrieve credentials via IMDS.

Kotlin implements credential provision based on these variables elsewhere, further up in the chain in `EcsCredentialsProvider`. The fact that the kotlin chain makes it all the way to the IMDS provider for you suggests to me that you're not using these environment variables to fetch credentials - ie. the provider in java v1 is branching to using IMDS.

From what I've seen in your logs and the code, I can form a few theories:
* The `IMDSv2` authentication flow isn't working as we expect. We don't support IMDSv1 like Java v1 does, so if that's the case, it would explain why Java v1 gets credentials, but Kotlin doesn't.
* Your application is trying to assume a role that isn't the one assigned to the node group that the container ends up on, and instead it's trying to get credentials in a way we're potentially not accounting for in Kotlin.

I can't find any literature that suggests that a container could be operating strictly using IMDSv1 (as in, token fetches for IMDSv2 would fail) but I can't discount it as a possibility.

Follow-up questions for you:
* Can you make the following cURL command within the container and see if you get a 200 response:
  `curl -X PUT -H "x-aws-ec2-metadata-token-ttl-seconds: 3600" 169.254.169.254/latest/api/token`
  this will verify whether fetching the IMDSv2 token is working as expected
* For the IAM role you've specified - is this role directly configured as the role to be used by the EKS node group on which the container ends up running, or are you injecting the credentials for it into the container in some other way?
* Can you provide the environment of the container (not the instance) in which your application is running (please remember to redact any sensitive or identifying values)
* Are you able to extend your sample to test retrieving credentials with Java SDK v2 (with debug instrumentation to see the provider it uses)

**Comment by vgiguere** [comment]
Sorry for the delay - vacations.

So I ran the CURL command from the container and this is what we get: **403**

`curl -X PUT -H "x-aws-ec2-metadata-token-ttl-seconds: 3600" 169.254.169.254/latest/api/token --verbose
*   Trying 169.254.169.254:80...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> PUT /latest/api/token HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.74.0
> Accept: */*
> x-aws-ec2-metadata-token-ttl-seconds: 3600
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< content-type: text/plain
< date: Wed, 20 Jul 2022 13:28:32 GMT
< server: EC2ws
< content-length: 0
<
* Connection #0 to host 169.254.169.254 left intact`


We are using `kube2iam` on our cluster, which proxies STS calls. 
These are the logs from it: 
`
time="2022-07-20T13:35:46Z" level=info msg="GET /latest/meta-data/iam/security-credentials/ (200) took 24100.000000 ns" req.method=GET req.path=/latest/meta-data/iam/security-credentials/ req.remote=10.1.45.173 res.duration=24100 res.status=200
time="2022-07-20T13:35:46Z" level=info msg="PUT /latest/api/token (403) took 872803.000000 ns" req.method=PUT req.path=/latest/api/token req.remote=10.1.45.173 res.duration=872803 res.status=403
time="2022-07-20T13:35:46Z" level=info msg="GET /latest/meta-data/iam/security-credentials/eg-trips-prod-migration-us-west-2-kmc-default (200) took 292763199.000000 ns" req.method=GET req.path=/latest/meta-data/iam/security-credentials/eg-trips-prod-migration-us-west-2-kmc-default req.remote=10.1.45.173 res.duration=2.92763199e+08 res.status=200
`

However when I run the same command from the underlying EC2 instance, it works: **200**

`
curl -X PUT -H "x-aws-ec2-metadata-token-ttl-seconds: 3600" 169.254.169.254/latest/api/token --verbose
*   Trying 169.254.169.254:80...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> PUT /latest/api/token HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.79.1
> Accept: */*
> x-aws-ec2-metadata-token-ttl-seconds: 3600
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Aws-Ec2-Metadata-Token-Ttl-Seconds: 3600
< Content-Length: 56
< Date: Wed, 20 Jul 2022 13:40:08 GMT
< Server: EC2ws
< Connection: close
< Content-Type: text/plain
<
* Closing connection 0
* `

**Comment by vgiguere** [comment]
It looks like the source of the issue is the `KUBE2IAM` pod, which proxies all STS calls on our cluster. The version we use (0.10.7) does not support IMDSv2 properly. 

I will try to the version bumped to 0.11.0 and report back in case other people have similar issues.
