### ISSUE TITLE
ClassNotFoundException: aws.smithy.kotlin.runtime.logging.Logger

### ISSUE THREAD

**Issue by jdpearce** [awslabs/aws-sdk-kotlin#755]
### Describe the bug

I'm trying to follow the [getting started tutorial](https://docs.aws.amazon.com/sdk-for-kotlin/latest/developer-guide/get-started.html#get-started-setup) and generate a jar file that I can execute.

I've implemented the example as given and when run in IntelliJ everything works correctly, but after I compile this to a jar and run it on the command line, I get this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: aws/smithy/kotlin/runtime/logging/Logger
        at aws.sdk.kotlin.runtime.config.profile.AwsConfigParserKt.<clinit>(AwsConfigParser.kt:212)
        at aws.sdk.kotlin.runtime.config.profile.AwsConfigLoaderKt.loadAwsProfiles(AwsConfigLoader.kt:48)
        at aws.sdk.kotlin.runtime.config.profile.AwsConfigLoaderKt$loadAwsProfiles$1.invokeSuspend(AwsConfigLoader.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at MainKt.main(Main.kt:19)
        at MainKt.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: aws.smithy.kotlin.runtime.logging.Logger
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 13 more
```

I will admit that I'm pretty new to Kotlin (and therefore also the Java ecosystem) so maybe I'm doing something wrong?

To compile to jar, I just added this section to `build.gradle.kts`

```
tasks.jar {
    manifest {
        attributes["Main-Class"] = "MainKt"
    }
    configurations["compileClasspath"].forEach { file: File ->
        from(zipTree(file.absoluteFile))
    }
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
```

### Expected behavior

No errors :)

### Current behavior

As above.

### Steps to Reproduce

n/a

### Possible Solution

n/a

### Context

n/a

### AWS Kotlin SDK version used

aws.sdk.kotlin:s3:0.17.12-beta

### Platform (JVM/JS/Native)

🤷‍♀️

### Operating System and version

macOS 12.6

**Comment by jdpearce** [comment]
@aajtodd Thank you so much. You filled in a few pieces that I just had no idea existed. The shadow plugin works brilliantly. 🙏
