### ISSUE TITLE
S3: putObject throws NoSuchMethodError exception

### ISSUE THREAD

**Issue by david-kubecka** [awslabs/aws-sdk-kotlin#765]
### Describe the bug

Simple code like this
```
S3Client.fromEnvironment()..putObject {
            bucket = "myBucket"
            key = "myObject"
            body = ByteStream.fromString("myContent")
        }
```
throws:
```
java.lang.NoSuchMethodError: 'okhttp3.Request$Builder okhttp3.Request$Builder.tag(kotlin.reflect.KClass, java.lang.Object)'
	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpUtilsKt.toOkHttpRequest(OkHttpUtils.kt:46)
	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.roundTrip(OkHttpEngine.kt:40)
	at aws.smithy.kotlin.runtime.http.SdkHttpClient$executeWithCallContext$2.invokeSuspend(SdkHttpClient.kt:54)
	at aws.smithy.kotlin.runtime.http.SdkHttpClient$executeWithCallContext$2.invoke(SdkHttpClient.kt)
	at aws.smithy.kotlin.runtime.http.SdkHttpClient$executeWithCallContext$2.invoke(SdkHttpClient.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at aws.smithy.kotlin.runtime.http.SdkHttpClient.executeWithCallContext(SdkHttpClient.kt:53)
	at aws.smithy.kotlin.runtime.http.SdkHttpClient.call(SdkHttpClient.kt:46)
	at aws.smithy.kotlin.runtime.http.SdkHttpClient.call(SdkHttpClient.kt:38)
	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt.httpTraceMiddleware(SdkOperationExecution.kt:187)
	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt.access$httpTraceMiddleware(SdkOperationExecution.kt:1)
	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$1.invoke(SdkOperationExecution.kt:76)
	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$1.invoke(SdkOperationExecution.kt:76)
	at aws.smithy.kotlin.runtime.io.middleware.MiddlewareLambda.handle(Middleware.kt:30)
	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
	at aws.smithy.kotlin.runtime.http.operation.HttpCallMiddleware.handle(SdkOperationExecution.kt:167)
	at aws.smithy.kotlin.runtime.http.operation.HttpCallMiddleware.handle(SdkOperationExecution.kt:158)
	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
	at aws.smithy.kotlin.runtime.io.middleware.Phase.handle(Phase.kt:64)
	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:146)
	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:135)
	at aws.smithy.kotlin.runtime.http.operation.FinalizeHandler.call(SdkOperationExecution.kt:132)
	at aws.smithy.kotlin.runtime.http.operation.FinalizeHandler.call(SdkOperationExecution.kt:129)
	at aws.smithy.kotlin.runtime.io.middleware.ModifyRequestMiddleware.handle(ModifyRequest.kt:24)
	at aws.smithy.kotlin.runtime.io.middleware.ModifyRequestMiddleware$handle$1.invokeSuspend(ModifyRequest.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
```

### Expected behavior

The code runs successfully.

### Current behavior

The code throws exception.

### Steps to Reproduce

- configure AWS environment
- run the above mentioned code

### AWS Kotlin SDK version used

0.17.12-beta

### Platform (JVM/JS/Native)

JVM (Kotlin 1.7.20)

### Operating System and version

MacOS 12.4

**Comment by aajtodd** [comment]
Could you share your build files/setup? 

Also could you dump the dependencies for your project?

e.g. for Gradle:
```
./gradlew dependencies --configuration runtimeClasspath
```

for Maven I believe the equivalent would be:
```
mvn dependency:tree
```

**Comment by david-kubecka** [comment]
Hi, attached is the dependency tree.
[dependency_tree.txt](https://github.com/awslabs/aws-sdk-kotlin/files/10149442/dependency_tree.txt)

**Comment by aajtodd** [comment]
I have been able to recreate this stack trace by forcing the `okhttp` version to 4.x

```kotlin
    implementation("com.squareup.okhttp3:okhttp:4.10.0") {
        version {
            strictly("4.10.0")
        }
    }
```

**Comment by AnneMayor** [comment]
Hi guys,
I am just make sure if this issue has been resolved.
If not, I would like to track it and resolve it if possible.
Is that okay for you?

**Comment by AnneMayor** [comment]
Hi guys,
I am just make sure if this issue has been resolved.
If not, I would like to track it and resolve it if possible.
Is that okay for you?

**Comment by ianbotsf** [comment]
We have no current plans to resolve this issue from the AWS SDK for Kotlin side. The SDK uses OkHttp **5.0.0-alpha.10** as its HTTP client. Any consumer which resolves to another version of OkHttp may find binary incompatibilities which manifest as errors such as `NoSuchMethodError`.

In general, dependency mismatches are a common problem and have a few common solutions for consumers:

* **Aligning dependency versions**. The simplest solution is to upgrade an explicit dependency (such as OkHttp) to match the version used by other dependencies (such as the AWS SDK for Kotlin). This may be as simple as removing `version.strictly` from the build configuration or may involve other mechanisms of version control within Gradle. This may not be possible when contenting with multiple dependencies which have transitive, incompatible dependencies (e.g., AWS SDK for Kotlin requires OkHttp **5.0.0-alpha.10**, some other third-party library requires a different version).
* **Shading dependencies**. The [Gradle Shadow plugin](https://github.com/johnrengelman/shadow) can be used to build uber JARs which bundle together a dependency closure (e.g., AWS SDK for Kotlin and all its dependencies) and relocate potentially-conflicting dependencies (e.g., OkHttp) into new namespaces. This could allow multiple versions of dependencies to be included simultaneously without conflicts.

The AWS SDK for Kotlin has no plans to downgrade OkHttp right now will continue to aggressively take new versions of dependencies during pre-production development (i.e., pre-GA/1.0). Post-GA, we will define a support matrix that identifies dependencies and a versioning strategy for them.

**Comment by johnsall** [comment]
@ianbotsf and @david-kubecka I was having the same issue (trying to use dynamo, not S3) and the solution that worked for me is this:

`implementation("aws.sdk.kotlin:dynamodb:0.22.1-beta"){
        exclude("com.squareup.okhttp3:okhttp")
    }
    implementation("com.squareup.okhttp3:okhttp:5.0.0-alpha.11")`

**Comment by kavithareddyedula** [comment]
having same issue : in my gradle com.squareup.okhttp3:okhttp: is  not used  .

Error:
nested exception is java.lang.NoSuchMethodError: 'okhttp3.Request$Builder okhttp3.Request$Builder.tag(kotlin.reflect.KClass, java.lang.Object

project  reference dependency :do i need to upgrade the following 
1. 
 plugins {
    id("kotlin-core") 
}.
2.
  implementation("com.amazonaws:aws-java-sdk-s3:1.12.336")
    implementation("com.amazonaws:aws-java-sdk-core:1.11.1034") i

**Comment by lauzadis** [comment]
@kavithareddyedula Those dependencies are on the Java SDK. Are you also using the Kotlin SDK (namespaced `aws.sdk.kotlin.*`)? 

If not, please look for solutions related to the Java SDK, and finally open a new issue with them if you are unable to solve your problem.

**Comment by kavithareddyedula** [comment]
yes  aws sdk is used . still no luck even after upgrading the 

   implementation("com.squareup.okhttp3:okhttp:okhttp:5.0.0-alpha.11")
====

import aws.sdk.kotlin.runtime.client.AwsClientOption
import aws.sdk.kotlin.runtime.endpoint.AwsEndpoint
import aws.sdk.kotlin.runtime.endpoint.AwsEndpointResolver
import aws.sdk.kotlin.services.s3.S3Client
import aws.sdk.kotlin.services.s3.model.*

this is the code :
 suspend fun putS3Object(bucketName: String, objectKey: String, objData: ByteArray): Boolean {
        val request = PutObjectRequest {
            bucket = bucketName
            key = objectKey
            body = ByteStream.fromBytes(objData)
        }
        client.use { s3 ->
            s3.putObject(request)
            return true
        }
    }

**Comment by ianbotsf** [comment]
@kavithareddyedula this issue is closed and likely isn't the best place to debug a new instance of `NoSuchMethodError`. If you're still seeing this issue after upgrading your dependencies, please [open a new issue](https://github.com/awslabs/aws-sdk-kotlin/issues/new/choose). To most efficiently debug this, plus include your complete list of dependencies (e.g., `./gradlew dependencies --configuration runtimeClasspath`) and a stack trace.

**Comment by schowave** [comment]
I was having the same issue and resolved it by using another HTTPClient:

  ```
dependencies {
      implementation("aws.smithy.kotlin:http-client-engine-crt:<version>")
  }
```

```
     S3Client.fromEnvironment {
            httpClient = CrtHttpEngine()
            region = "eu-central-1"
        }.use { s3 ->
            val response = s3.putObject(request)
            logger.info("Tag information is ${response.eTag}")
        }
```
        
        This is described here:
        https://github.com/awslabs/aws-sdk-kotlin/blob/main/docs/howto/configuring/http-clients.md

**Comment by lauzadis** [comment]
Hello, we've released a new HTTP engine that is based on OkHttp3 4.x. [Check out the module's README](https://github.com/smithy-lang/smithy-kotlin/tree/main/runtime/protocol/http-client-engines/http-client-engine-okhttp4) which includes some important configuration steps. This should allow you to completely remove the dependency on OkHttp 5.0.0-alpha.X. If you have any problems, [please open a new issue](https://github.com/awslabs/aws-sdk-kotlin/issues/new/choose).
