### ISSUE TITLE
Previously working interaction between DynamoDB, SecretsManager, and CredentialsProvider throws a java.lang.IllegalStateException.

### ISSUE THREAD

**Issue by adamsite999** [awslabs/aws-sdk-kotlin#789]
### Describe the bug

The code below works with 0.17.12-beta and does not work with 0.18.0 or 0.19.0. This code uses an implemented CredentialsProvider to pass credentials to DynamoDB by retrieving a database credential via AWS SecretsManager.

### Expected behavior

This should retrieve the item from DynamoDB via getItem using the credential password retrieved from SecretsManager.

### Current behavior

An exception is thrown when the secretsmanager client attempts to retrieve the secret value.

java.lang.IllegalStateException: This method may only be called when no current span exists or the new span is a child of the active span
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                                                                                    Caused by: java.lang.IllegalStateException: This method may only be called when no current span exists or the new span is a child of the active span
                                                                                                    	at aws.sdk.kotlin.services.secretsmanager.DefaultSecretsManagerClient.getSecretValue(DefaultSecretsManagerClient.kt:1160)
                                                                                                    	at com.aws_test.MyAWSCredentialProvider.getCredentials(MainActivity.kt:50)
                                                                                                    	at aws.sdk.kotlin.runtime.auth.credentials.internal.BorrowedCredentialsProvider.getCredentials(Unknown Source:2)
                                                                                                    	at aws.smithy.kotlin.runtime.auth.awssigning.DefaultAwsSignerImpl.sign(DefaultAwsSigner.kt:28)
                                                                                                    	at aws.smithy.kotlin.runtime.auth.awssigning.middleware.AwsSigningMiddleware.modifyRequest(AwsSigningMiddleware.kt:161)
                                                                                                    	at aws.smithy.kotlin.runtime.auth.awssigning.middleware.AwsSigningMiddleware.modifyRequest(AwsSigningMiddleware.kt:22)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.ModifyRequestMiddleware.handle(ModifyRequest.kt:24)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.Phase.handle(Phase.kt:64)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.MutateHandler.call(SdkOperationExecution.kt:122)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.MutateHandler.call(SdkOperationExecution.kt:119)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.ModifyRequestMiddleware.handle(ModifyRequest.kt:24)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.ModifyRequestMiddleware.handle(ModifyRequest.kt:24)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.ModifyRequestMiddleware.handle(ModifyRequest.kt:24)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                                                                                                    	at aws.smithy.kotlin.runtime.http.middleware.Retry$handle$outcome$1$invokeSuspend$$inlined$withChildTraceSpan$1.invokeSuspend(CoroutineContextUtils.kt:228)
                                                                                                    	at aws.smithy.kotlin.runtime.http.middleware.Retry$handle$outcome$1$invokeSuspend$$inlined$withChildTraceSpan$1.invoke(Unknown Source:8)
                                                                                                    	at aws.smithy.kotlin.runtime.http.middleware.Retry$handle$outcome$1$invokeSuspend$$inlined$withChildTraceSpan$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at aws.smithy.kotlin.runtime.http.middleware.Retry$handle$outcome$1.invokeSuspend(Retry.kt:96)
                                                                                                    	at aws.smithy.kotlin.runtime.http.middleware.Retry$handle$outcome$1.invoke(Unknown Source:8)
                                                                                                    	at aws.smithy.kotlin.runtime.http.middleware.Retry$handle$outcome$1.invoke(Unknown Source:2)
2022-12-02 14:52:09.495  5340-5340  AndroidRuntime          pid-5340                             E  	at aws.smithy.kotlin.runtime.retries.StandardRetryStrategy.doTryLoop(StandardRetryStrategy.kt:51)
                                                                                                    	at aws.smithy.kotlin.runtime.retries.StandardRetryStrategy.retry(StandardRetryStrategy.kt:32)
                                                                                                    	at aws.smithy.kotlin.runtime.http.middleware.Retry.handle$suspendImpl(Retry.kt:42)
                                                                                                    	at aws.smithy.kotlin.runtime.http.middleware.Retry.handle(Unknown Source:0)
                                                                                                    	at aws.sdk.kotlin.runtime.http.middleware.AwsRetryMiddleware.handle(AwsRetryMiddleware.kt:38)
                                                                                                    	at aws.sdk.kotlin.runtime.http.middleware.AwsRetryMiddleware.handle(AwsRetryMiddleware.kt:30)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                                                                                                    	at aws.sdk.kotlin.services.dynamodb.endpoints.internal.ResolveEndpointMiddleware$install$2.invokeSuspend(ResolveEndpointMiddleware.kt:31)
                                                                                                    	at aws.sdk.kotlin.services.dynamodb.endpoints.internal.ResolveEndpointMiddleware$install$2.invoke(Unknown Source:13)
                                                                                                    	at aws.sdk.kotlin.services.dynamodb.endpoints.internal.ResolveEndpointMiddleware$install$2.invoke(Unknown Source:6)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.MiddlewareLambda.handle(Middleware.kt:30)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.Phase.handle(Phase.kt:64)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.SerializeHandler.call(SdkOperationExecution.kt:115)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.SerializeHandler.call(SdkOperationExecution.kt:103)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.InitializeHandler.call(SdkOperationExecution.kt:100)
                                                                                                    	at aws.sdk.kotlin.services.dynamodb.endpoints.internal.ResolveEndpointMiddleware$install$1.invokeSuspend(ResolveEndpointMiddleware.kt:25)
                                                                                                    	at aws.sdk.kotlin.services.dynamodb.endpoints.internal.ResolveEndpointMiddleware$install$1.invoke(Unknown Source:13)
                                                                                                    	at aws.sdk.kotlin.services.dynamodb.endpoints.internal.ResolveEndpointMiddleware$install$1.invoke(Unknown Source:6)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.MiddlewareLambda.handle(Middleware.kt:30)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.Phase.handle(Phase.kt:64)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.SdkHttpOperationKt.execute(SdkHttpOperation.kt:84)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.SdkHttpOperationKt.roundTrip(SdkHttpOperation.kt:67)
                                                                                                    	at aws.sdk.kotlin.services.dynamodb.DefaultDynamoDbClient$getItem$$inlined$withRootTraceSpan$1.invokeSuspend(CoroutineContextUtils.kt:215)
                                                                                                    	at aws.sdk.kotlin.services.dynamodb.DefaultDynamoDbClient$getItem$$inlined$withRootTraceSpan$1.invoke(Unknown Source:8)
                                                                                                    	at aws.sdk.kotlin.services.dynamodb.DefaultDynamoDbClient$getItem$$inlined$withRootTraceSpan$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at aws.sdk.kotlin.services.dynamodb.DefaultDynamoDbClient.getItem(DefaultDynamoDbClient.kt:2733)
                                                                                                    	at com.aws_test.MainActivity$onCreate$1.invokeSuspend(MainActivity.kt:32)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
                                                                                                    	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                                                                                                    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                                                                                                    	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                                                                                                    	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                                                                                                    	at com.aws_test.MainActivity.onCreate(MainActivity.kt:31)

### Steps to Reproduce

To reproduce this, create an empty activity project in Android Studio. Use the code provided for MainActivity.kt, build.gradle, and AndroidManifest.xml. The entries in build.gradle can be changed to 0.17.12 to see that the code works as expected. The AndroidManifest entry is just there to allow the INTERNET permission.

You will have to enter your own existing AWS SecretsManager credentials and DynamoDb table names.

[aws_test.zip](https://github.com/awslabs/aws-sdk-kotlin/files/10147597/aws_test.zip)

### Context

Ideally, I should be able to use a secretValue retrieved from AWS secrets manager to authenticate my DynamoDB client. That way I can rotate database credentials without affecting app functionality.

### AWS Kotlin SDK version used

0.17.12, 0.18.0, and 0.19.0

### Platform (JVM/JS/Native)

Multiple

### Operating System and version

Multiple

**Comment by aajtodd** [comment]
@adamsite999 Thanks for the report. This appears to stem from the new tracing APIs added in `0.18.0`. We should have a fix for this in this weeks release.

**Comment by aajtodd** [comment]
Fix for this should be in the next release later this week.

**Comment by adamsite999** [comment]
Thanks for the update! :-)
-------- Original message --------From: Aaron Todd ***@***.***> Date: 12/6/22  07:08  (GMT-06:00) To: awslabs/aws-sdk-kotlin ***@***.***> Cc: adamsite999 ***@***.***>, Mention ***@***.***> Subject: Re: [awslabs/aws-sdk-kotlin] Previously working interaction between DynamoDB, SecretsManager, and CredentialsProvider throws a java.lang.IllegalStateException. (Issue #789) 
Fix for this should be in the next release later this week.

**Comment by aajtodd** [comment]
As an FYI this didn't go out this week due to an unrelated bug. Will be in next weeks release.

**Comment by adamsite999** [comment]
No worries. Thank you for the update.~Adam 
-------- Original message --------From: Aaron Todd ***@***.***> Date: 12/9/22  16:16  (GMT-06:00) To: awslabs/aws-sdk-kotlin ***@***.***> Cc: adamsite999 ***@***.***>, Mention ***@***.***> Subject: Re: [awslabs/aws-sdk-kotlin] Previously working interaction between DynamoDB, SecretsManager, and CredentialsProvider throws a java.lang.IllegalStateException. (Issue #789) 
As an FYI this didn't go out this week due to an unrelated bug. Will be in next weeks release.
