### ISSUE TITLE
S3 UploadPart API throws an exceptions with acceleration mode enabled.

### ISSUE THREAD

**Issue by sdhuka** [awslabs/aws-sdk-kotlin#862]
### Describe the bug

S3 UploadPart API throws an exceptions with acceleration mode enabled

```
System.out                          com.amplifyframework.storage.s3.test           I  ERROR/amplify:aws-s3-storage:PartUploadTransferWorker: PartUploadTransferWorker failed with exception: aws.sdk.kotlin.services.s3.model.S3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.
System.out                          com.amplifyframework.storage.s3.test           I  	at aws.sdk.kotlin.services.s3.transform.UploadPartOperationDeserializerKt.throwUploadPartError(UploadPartOperationDeserializer.kt:63)
System.out                          com.amplifyframework.storage.s3.test           I  	at aws.sdk.kotlin.services.s3.transform.UploadPartOperationDeserializerKt.access$throwUploadPartError(UploadPartOperationDeserializer.kt:1)
System.out                          com.amplifyframework.storage.s3.test           I  	at aws.sdk.kotlin.services.s3.transform.UploadPartOperationDeserializerKt$throwUploadPartError$1.invokeSuspend(Unknown Source:13)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### Expected behavior

UploadPart API should support acceleration endpoint.

### Current behavior

Mulitpart upload fails with acceleration mode enabled because `UploadPart` api throw following exception.`createMultipartUpload` works as expected with acceleration mode enabled but `UploadPart`. Same code works fine for successfully uploading a file using multipart upload without acceleration mode enabled.

```
System.out                          com.amplifyframework.storage.s3.test           I  ERROR/amplify:aws-s3-storage:PartUploadTransferWorker: PartUploadTransferWorker failed with exception: aws.sdk.kotlin.services.s3.model.S3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.
System.out                          com.amplifyframework.storage.s3.test           I  	at aws.sdk.kotlin.services.s3.transform.UploadPartOperationDeserializerKt.throwUploadPartError(UploadPartOperationDeserializer.kt:63)
System.out                          com.amplifyframework.storage.s3.test           I  	at aws.sdk.kotlin.services.s3.transform.UploadPartOperationDeserializerKt.access$throwUploadPartError(UploadPartOperationDeserializer.kt:1)
System.out                          com.amplifyframework.storage.s3.test           I  	at aws.sdk.kotlin.services.s3.transform.UploadPartOperationDeserializerKt$throwUploadPartError$1.invokeSuspend(Unknown Source:13)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
System.out                          com.amplifyframework.storage.s3.test           I  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

Code Snippet for Part Upload
```
s3Client.withConfig {
            interceptors += UploadProgressListenerInterceptor(partUploadProgressListener)
            enableAccelerate = true
        }.uploadPart {
            bucket = bucketName
            key = key
            uploadId = multiPartUploadId
            body = File(transferRecord.file).asByteStream(
                start = transferRecord.fileOffset,
                fileOffset + bytesTotal - 1
            )
            partNumber = partNumber
        }.let { response -> }
```

### Steps to Reproduce

Start multi-part upload with config override `enableAccelerate = true` and observe the error.

### Possible Solution

N/A

### Context

Adding support for S3 acceleration mode in Amplify library.

### AWS Kotlin SDK version used

0.20.3-beta

### Platform (JVM/JS/Native)

Native

### Operating System and version

Android 31

**Comment by sdhuka** [comment]
@ianbotsf Thanks for looking into it, here is the code for [progress listener interceptor](https://github.com/aws-amplify/amplify-android/blob/sdhuka/s3-accelerate/aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/ProgressListenerHttpInterceptor.kt)

**Comment by ianbotsf** [comment]
Received logs offline and traced the problem to the new `Expect: 100-continue` header added to S3 PUT requests over 2MB (#845). This header is being erroneously included in the SigV4 signature but it is not meant to be. Seemingly, this isn't a problem when using conventional S3 endpoints—only when using acceleration-enabled endpoints.

A fix to the signing logic will need to be released. In the meantime, this error can be worked around by disabling the continue header altogether via the following configuration option:

```kotlin
val s3Client = S3Client.fromEnvironment {
    // ...other config options...
    continueHeaderThresholdBytes = null // Temporarily disable continue header
}
```
