### ISSUE TITLE
When using ifModifiedSince parameter of GetObject with non-null value, SDK throws S3Exception

### ISSUE THREAD

**Issue by eiennohito** [awslabs/aws-sdk-kotlin#863]
### Describe the bug

GetObject with ifModifiedSince flag throws an exception

### Expected behavior

There should not be any exception thrown, but metadata should be present in the response

### Current behavior

```
Exception in thread "main" aws.sdk.kotlin.services.s3.model.S3Exception: Failed to parse response as 'restXml' error
	at aws.sdk.kotlin.services.s3.transform.GetObjectOperationDeserializerKt.throwGetObjectError(GetObjectOperationDeserializer.kt:101)
	at aws.sdk.kotlin.services.s3.transform.GetObjectOperationDeserializerKt.access$throwGetObjectError(GetObjectOperationDeserializer.kt:1)
	at aws.sdk.kotlin.services.s3.transform.GetObjectOperationDeserializer.deserialize(GetObjectOperationDeserializer.kt:32)
	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:92)
	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:92)
	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:148)
	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler$call$1.invokeSuspend(SdkOperationExecution.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at test(test.kt:141)

Caused by: java.lang.IllegalStateException: unable to parse error from empty response
	at aws.sdk.kotlin.services.s3.transform.GetObjectOperationDeserializerKt.throwGetObjectError(GetObjectOperationDeserializer.kt:97)
	... 22 more
```

### Steps to Reproduce

```kotlin
val s3 = S3Client { region = "us-west1" }

val req = GetObjectRequest {
      this.bucket = bucket
      this.key = key
      this.ifModifiedSince = Instant.ofEpochMilli(0).toSdkInstant()
  }

  s3.getObject(req) {
      println(it)
  }
```

### AWS Kotlin SDK version used

0.19.5-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Linux

**Comment by aajtodd** [comment]
I haven't been able to recreate this, would you mind sharing some additional logs or details about your setup/deployment?

e.g. by turning on verbose request/response logging:

```kotlin
    S3Client {
        sdkLogMode = SdkLogMode.LogResponseWithBody + SdkLogMode.LogResponseWithBody
    }

```

Please strip any sensitive information/replace with `<redacted>` as appropriate.
