### ISSUE TITLE
S3 upload failure

### ISSUE THREAD

**Issue by sdhuka** [awslabs/aws-sdk-kotlin#948]
### Describe the bug

Upload to S3 fails with following exception.  aws-amplify/amplify-android/#2472
```
Caused by: java.io.IOException: kotlinx.coroutines.JobCancellationException: Parent job is Completed; job=JobImpl{Completed}@26f1238
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.ByteChannelRequestBody.writeTo(ByteChannelRequestBody.kt:39)
                                                                                                    	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:62)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:57)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at com.android.tools.appinspection.network.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.kt:52)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
```

### Expected behavior

Upload to S3 should not result in error

### Current behavior

Upload to S3 fails due to exception.

### Steps to Reproduce

```
s3Client.withConfig {
            interceptors += UploadProgressListenerInterceptor(uploadProgressListener)
            enableAccelerate = transferRecord.useAccelerateEndpoint == 1
        }.putObject(putObjectRequest).let {
            Result.success(outputData)
}
```
Upload Interceptor: https://github.com/aws-amplify/amplify-android/blob/main/aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/ProgressListenerHttpInterceptor.kt#L125

### AWS Kotlin SDK version used

0.21.1-beta

### Platform (JVM/JS/Native)

Native

### Operating System and version

Android 31

**Comment by sdhuka** [comment]
original issue in Amplify Android SDK: aws-amplify/amplify-android#2472
